Repository BHoM/BHoM_Engine, pull requests merged in 2019-09, with the labels that each got.

#1161 Reflection_Engine: added methods' inputs parameters names in menu description
  Reflection_Engine/Convert/ToText.cs
Labels: type:feature

#1169 Planning_Engine : Update Create method to include Description Property
  Planning_Engine/Create/Milestone.cs
Labels: type:feature

#1172 Reflection_Engine: shorten the params input description if longer than a max value
  Reflection_Engine/Convert/ToText.cs
Labels: type:bug

#1187 Environment Engine Exposed tolerance parameter for NormalAwayFromSpace
  Environment_Engine/Query/NormalAwayFromSpace.cs
Labels: type:feature

#1143 Structure_Engine: Closes #1127 Adds name to create method for RigidLink
  Structure_Engine/Create/RigidLink.cs
Labels: severity:low, size:XS, type:feature

#1202 Common_Engine: Add Translate Methods For IElements
  Common_Engine/Common_Engine.csproj
  Common_Engine/Modify/TranslateIElements.cs
Labels: severity:low, size:S, type:feature

#1209 Environment_Engine: expose multiple tolerance to prevent incorrect opening additions
  Environment_Engine/Modify/AddOpening.cs
Labels: type:bug

#1208 BHoM_Engine: fix fragment adding bug
  BHoM_Engine/Modify/AddFragment.cs
Labels: type:bug

#1220 Structure_Engine: Updating Geometry(this ISectionProperty section) to IGeometry(this ISectionProperty section)
  Structure_Engine/Query/Geometry.cs
Labels: severity:critical, type:compliance

#1223 Reflection_Engine: CreateType throws exeptions that stop the data flow in visual programming if in a loop
  Reflection_Engine/Create/Type.cs
Labels: type:compliance

#1222 Serialiser_Engine: Fix ToJson() method for when input is null
  Serialiser_Engine/Convert/Json.cs
Labels: type:bug

#1228 Structure_Engine: #1227 CoordinateSystem from bar
  Structure_Engine/Query/CoordinateSystem.cs
Labels: type:feature
