Repository BHoM/BHoM_Engine, pull requests merged in 2019-07, with the labels that each got.

#1070 BHoM_Engine: Add issue templates
  .github/ISSUE_TEMPLATE/api_changed.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/compliance.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/test_script.md
Labels: size:XS

#1068 Environment_Engine: Add method to modify panels and fix their normals
  Environment_Engine/Environment_Engine.csproj
  Environment_Engine/Modify/FixNormal.cs
Labels: severity:low

#1074 Environment_Engine: Resolve floor geometry issues
  Environment_Engine/Query/FloorGeometry.cs
Labels: severity:critical

#1080 Environment_Engine: Temporary fix of #1078 - more to do for proper though
  Environment_Engine/Create/Gain.cs
Labels: size:S

#1083 Environment_Engine: Gain creation methods and a calculation method for lighting gain
  Environment_Engine/Compute/LightingGain.cs
  Environment_Engine/Create/Gain.cs
  Environment_Engine/Create/Gains.cs
  Environment_Engine/Environment_Engine.csproj
Labels: size:S

#1082 Reflection_Engine: Issue1081-RemoveLoggingForGetPropertyAndCustomObjects
  Reflection_Engine/Query/PropertyValue.cs
Labels: type:bug

#1089 BHoM_Engine-#1088-DeleteBHoM_Engine.nuspec
  BHoM_Engine/BHoM_Engine.nuspec
Labels: severity:critical, type:bug

#1102 EnvironmentEngine: Add People Gain and Occupancy Compute
  Environment_Engine/Compute/Occupancy.cs
  Environment_Engine/Compute/PeopleGain.cs
  Environment_Engine/Environment_Engine.csproj
Labels: type:feature

#1122 Environment_Engine: Fix Polyline crash bug
  Environment_Engine/Query/Polyline.cs
Labels: type:bug

#1123 Environment_Engine: Add defaults for gain computes to allow gains to be returned
  Environment_Engine/Compute/EquipmentGain.cs
  Environment_Engine/Compute/LightingGain.cs
  Environment_Engine/Compute/PeopleGain.cs
  Environment_Engine/Compute/PlugGain.cs
Labels: size:XS
