Repository BHoM/BHoM_Engine, pull requests merged in 2019-12, with the labels that each got.

#1364 Structure_Engine: Correct description for Shear Modulus in Timber Constructor
  Structure_Engine/Create/MaterialFragment.cs
Labels: severity:low, size:XS, type:documentation

#1373 Fixes #1372
  Reflection_Engine/Query/IsDeprecated.cs
Labels: severity:critical, type:bug

#1377 Revert "Fixes #1372"
  Reflection_Engine/Query/IsDeprecated.cs
Labels: severity:critical, type:bug

#1350 Structure_Engine: DeformedShape to be using BarDisplacements instead of BarDeformations
  Structure_Engine/Query/DeformedShape.cs
Labels: type:feature

#1390 Environment_Engine Change tolerance default for FloorGeometry
  Environment_Engine/Query/FloorGeometry.cs
Labels: type:compliance

#1388 Reflection_Engine: Make sure PropertyInfo have a line describing their type
  Reflection_Engine/Query/Description.cs
Labels: type:feature
