Repository BHoM/BHoM_Engine, pull requests merged in 2019-05, with the labels that each got.

#926 Common_Engine-Issue925-AddLengthIElement1DMethod
  Common_Engine/Common_Engine.csproj
  Common_Engine/Query/Length.cs
Labels: severity:medium, size:S, type:feature

#942 Geometry_Engine-Issue941-AddBooleanIntersectionForBoundingBoxes
  Geometry_Engine/Compute/BooleanIntersection.cs
Labels: severity:low, size:M, status:parked, type:feature

#961 Geometry_Engine: Issue918 Update IsContaining for BoundingBoxes
  Geometry_Engine/Query/IsContaining.cs
Labels: severity:medium, size:S, type:bug, type:feature

#986 Reflection_Engine: Add IsDeprecated interface method
  Reflection_Engine/Query/IsDeprecated.cs
Labels: severity:critical, type:feature

#988 Geometry_EngineL: issue 905 - FitPlane doesn't always produce correct plane
  Geometry_Engine/Compute/FitPlane.cs
Labels: severity:critical, size:S, type:bug
