Repository BHoM/BHoM_Engine, pull requests merged in 2019-01, with the labels that each got.

#766 Reflection_Engine - Issue 765 - Method to get the current location of the executing BHoM dlls
  Reflection_Engine/Query/CurrentAssemblyFolder.cs
  Reflection_Engine/Reflection_Engine.csproj
Labels: feature_minor

#769 Serialisation of IImmutable objects, Issue 767
  Serialiser_Engine/Objects/MemberMapConventions/ImmutableBHoMClassMapConvention.cs
Labels: bug_critical

#775 Create PULL_REQUEST_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: compliance

#778 Bug in translate for CoordinateSystem.Cartesian
  Geometry_Engine/Modify/Translate.cs
Labels: bug_critical
