Repository BHoM/BHoM_Engine, pull requests merged in 2019-06, with the labels that each got.

#994 Geometry_Engine: issues 992,993, Normal(Arc), PointAtParameter(Arc)
  Geometry_Engine/Modify/SplitAtPoints.cs
  Geometry_Engine/Query/PointAtParameter.cs
Labels: severity:medium, size:S, type:bug

#1034 Environment_Engine: Add methods for changing adjacent space names
  Environment_Engine/Modify/AdjacentSpace.cs
Labels: type:feature

#1040 Environment_Engine: Fix handling null constructions
  Environment_Engine/Query/UniqueConstructions.cs
Labels: severity:critical, size:XS

#1036 Environment_Engine: Align to BHoM fragments
  Environment_Engine/Modify/AddFragment.cs
  Environment_Engine/Modify/Copy.cs
  Environment_Engine/Query/FindFragment.cs
  Environment_Engine/Query/ObjectsByFragment.cs
  Environment_Engine/Query/Openings.cs
  Environment_Engine/Query/Panels.cs
  Environment_Engine/Query/Spaces.cs
Labels: size:XS

#1042 Environment_Engine: Floor geometry method fix
  Environment_Engine/Query/FloorGeometry.cs
Labels: size:M

#1062 Reflection_Engine - Issue 1003 - Extract interface types
  Reflection_Engine/Query/TypeList.cs
Labels: severity:critical, type:feature

#1064 Structure_Engine: Ensure new GUIDs for Edges
  Structure_Engine/Modify/SetGeometry.cs
  Structure_Engine/Modify/SetOutlineElements1D.cs
Labels: severity:medium, size:S, type:bug
