Repository BHoM/BHoM_Engine, pull requests merged in 2019-04, with the labels that each got.

#890 Environment_Engine-Issue888-MakeSetInternalElements2DNotReturnNull
  Environment_Engine/Modify/SetInternalElements2D.cs
Labels: size:XS, type:compliance

#891 Structure_Engine-Issue887-MakeSetInternalElements2DNotReturnNull
  Structure_Engine/Modify/SetInternalElements2D.cs
Labels: size:XS, type:compliance

#907 Serialiser_Engine: Return list when FromJson parses a json array
  Serialiser_Engine/Convert/Json.cs
Labels: severity:critical, size:S, type:bug

#909 Library_Engine : Update Planning.Labels Datasets
  Library_Engine/DataSets/Planning/Labels/IssueLabels.json
Labels: size:S, type:compliance

#911 Add simple Create Employee method
  Humans_Engine/Create/Employee.cs
  Humans_Engine/Humans_Engine.csproj
Labels: size:XS, type:feature
