Repository BHoM/BHoM_Engine, pull requests merged in 2019-02, with the labels that each got.

#782 Serialiser_Engine - Issue 302 - Convert unknown objects into custom objects
  Serialiser_Engine/Convert/Bson.cs
  Serialiser_Engine/Objects/BsonSerializers/CustomObjectSerializer.cs
  Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs
Labels: feature

#784 Create CODEOWNERS file in docs/
  docs/CODEOWNERS
Labels: documentation

#801 Centring Sections around the origin
  Structure_Engine/Compute/Integrate.cs
  Structure_Engine/Create/ConcreteSection.cs
  Structure_Engine/Create/SteelSection.cs
Labels: bug, feature

#807 Fix #806 - match spaces method
  Environment_Engine/Query/MatchSpace.cs
  Environment_Engine/Query/Spaces.cs
Labels: bug_critical

#824 Resolve #821 - exposed to sun parameter
  Environment_Engine/Query/ExposedToSun.cs
Labels: bug_critical

#823 Reflection_Engine: Empty checks for attributes
  Reflection_Engine/Query/Description.cs
  Reflection_Engine/Query/OutputDescription.cs
Labels: feature

#834 BHoM_Engine- Adding filter and group by type methods
  BHoM_Engine/BHoM_Engine.csproj
  BHoM_Engine/Query/FilterByType.cs
  BHoM_Engine/Query/GroupByType.cs
Labels: feature

#842 Reflection_Engine - Warning message for set property
  Reflection_Engine/Modify/SetPropertyValue.cs
Labels: feature
