Repository BHoM/BHoM_Engine, pull requests merged in 2019-11, with the labels that each got.

#1300 Diffing_Engine: Remove reference to Testing oM
  Diffing_Engine/Diffing_Engine.csproj
Labels: size:XS, type:compliance

#1304 Environment_Engine: Adding manipulation and query methods
  Environment_Engine/Environment_Engine.csproj
  Environment_Engine/Modify/RemoveOpenings.cs
  Environment_Engine/Modify/SplitOpening.cs
  Environment_Engine/Modify/SplitPanels.cs
  Environment_Engine/Query/Openings.cs
Labels: type:compliance, type:feature

#1309 Geometry_Engine: Make use of parameters in CleanPolyline
  Geometry_Engine/Modify/CleanPolyline.cs
  Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs
Labels: size:XS, type:feature

#1311 Environment_Engine: fix NormalAwayFromSpace bug
  Environment_Engine/Query/IsContaining.cs
Labels: type:bug

#1252 Geometry_Engine: Ensures all section profile constructors are correct
  Geometry_Engine/Create/ShapeProfile.cs
Labels: type:bug

#1308 Geometry_Engine: Add fallback cases and support for Basis in Clone.cs
  Geometry_Engine/Query/Clone.cs
Labels: type:bug

#1301 Serialiser_Engine: Handle the case of a class containing another class that was only changed internally
  Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs
Labels: type:feature

#1328 Geometry_Engine CurveProximity, return single point twice for intersection events
  Geometry_Engine/Compute/CurveProximity.cs
Labels: type:bug

#1335 Reflection_Engine: Add possibility to include full path for parameters in method.ToText()
  Reflection_Engine/Convert/ToText.cs
Labels: type:feature

#1338 Serialiser_Engine: Remove attempt to re-deserialise a custom object
  Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs
Labels: severity:critical, type:bug

#1341 Serialiser_Engine: Fix deserialisation of generic types
  Reflection_Engine/Compute/UnqualifiedName.cs
  Reflection_Engine/Reflection_Engine.csproj
  Serialiser_Engine/Objects/MemberMapConventions/GenericDiscriminatorConvention.cs
Labels: type:bug

#1346 Reflection_Engine: Remove the instance from the list of arguments when calculating an instance method
  Reflection_Engine/Convert/ToFunc.cs
Labels: severity:critical, type:bug

#1354 Geometry_Engine updated output documentation
  Geometry_Engine/Query/Angle.cs
Labels: type:documentation

#1356 Environment_Engine: SpaceTime create-method now assigns hour-values correctly
  Environment_Engine/Create/SpaceTime.cs
Labels: type:bug
