Repository BHoM/BHoM_Engine, pull requests merged in 2019-10, with the labels that each got.

#1224 Geometry_Engine #1096 - Fix BooleanUnion bug
  Geometry_Engine/Compute/BooleanUnion.cs
Labels: severity:low, size:XS, type:bug

#1238 Update code owners
  docs/CODEOWNERS
Labels: size:XS, type:compliance

#1226 Geometry_Engine - Fix SplitAtPoints() bugs and change output type
  Geometry_Engine/Modify/SplitAtPoints.cs
Labels: severity:low, size:S, type:bug

#1240 Geometry_Engine - Grid is missing Geometry method
  Geometry_Engine/Query/Geometry.cs
Labels: severity:critical, type:bug

#1259 Update assembly version
  Acoustic_Engine/Properties/AssemblyInfo.cs
  Analytical_Engine/Properties/AssemblyInfo.cs
  Architecture_Engine/Properties/AssemblyInfo.cs
  BHoM_Engine/Properties/AssemblyInfo.cs
  Common_Engine/Properties/AssemblyInfo.cs
  Data_Engine/Properties/AssemblyInfo.cs
  Diffing_Engine/Properties/AssemblyInfo.cs
  Engine_Test/Properties/AssemblyInfo.cs
  Environment_Engine/Properties/AssemblyInfo.cs
  Geometry_Engine/Properties/AssemblyInfo.cs
  Humans_Engine/Properties/AssemblyInfo.cs
  Library_Engine/Properties/AssemblyInfo.cs
  Physical_Engine/Properties/AssemblyInfo.cs
  Planning_Engine/Properties/AssemblyInfo.cs
  Reflection_Engine/Properties/AssemblyInfo.cs
  Results_Engine/Properties/AssemblyInfo.cs
  SVG_Engine/Properties/AssemblyInfo.cs
  Serialiser_Engine/Properties/AssemblyInfo.cs
  Speech_Engine/Properties/AssemblyInfo.cs
  Structure_Engine/Properties/AssemblyInfo.cs
  Testing_Engine/Properties/AssemblyInfo.cs
  Units_Engine/Properties/AssemblyInfo.cs
Labels: type:compliance

#1268 Structure_Engine: Add Create methods for ContourLoads and GeoemetricalLineLoad
  Structure_Engine/Create/Load.cs
Labels: type:external-api-changes

#1276 Reflection_Engine: Add a ToText() method for MemberInfo
  Reflection_Engine/Convert/ToText.cs
Labels: type:feature

#1281 Environment_Engine: Update fragments
  Environment_Engine/Create/BuildingAnalyticalFragment.cs
  Environment_Engine/Create/BuildingContextFragment.cs
  Environment_Engine/Create/BuildingResultFragment.cs
  Environment_Engine/Create/CoefficientFragment.cs
  Environment_Engine/Create/EnvironmentConstructionFragment.cs
  Environment_Engine/Create/LightReflectanceFragment.cs
  Environment_Engine/Create/LightTransmittanceFragment.cs
  Environment_Engine/Create/OriginContextFragment.cs
  Environment_Engine/Create/PanelAnalyticalFragment.cs
  Environment_Engine/Create/PanelContextFragment.cs
  Environment_Engine/Create/RadiationFragment.cs
  Environment_Engine/Create/SpaceAnalyticalFragment.cs
  Environment_Engine/Create/SpaceContextFragment.cs
Labels: type:compliance
