Repository BHoM/BHoM_Engine, pull requests merged in 2020-08, with the labels that each got.

#1926 Structure_Engine: Small improvements to torsion constant calculations
  Structure_Engine/Query/TorsionalConstant.cs
Labels: type:feature

#1931 Environment_Engine: Provide protection around some aspects of engine code
  Environment_Engine/Query/BottomLeft.cs
  Environment_Engine/Query/BottomRight.cs
  Environment_Engine/Query/NormalAwayFromSpace.cs
  Environment_Engine/Query/TopRight.cs
Labels: type:bug

#1921 Data_Engine: Uncommenting code for getting all values from a Table
  Data_Engine/Query/Values.cs
Labels: type:bug

#1945 Environment_Engine: Align to oM changes
  Environment_Engine/Compute/EquipmentGain.cs
  Environment_Engine/Compute/LightingGain.cs
  Environment_Engine/Compute/Occupancy.cs
  Environment_Engine/Compute/PeopleGain.cs
  Environment_Engine/Compute/PlugGain.cs
  Environment_Engine/Create/Gains.cs
  Environment_Engine/Create/Space.cs
  Environment_Engine/Environment_Engine.csproj
Labels: type:external-api-changes
