Repository BHoM/BHoM_Engine, pull requests merged in 2020-05, with the labels that each got.

#1727 Environment_Engine: Add OpeningsByType Query method
  Environment_Engine/Environment_Engine.csproj
  Environment_Engine/Query/OpeningsByType.cs
Labels: type:feature

#1700 Update README.md
  README.md
Labels: type:documentation

#1732 Reflection_Engine: Fix MethodBase() method
  Reflection_Engine/Create/MethodBase.cs
Labels: type:bug

#1745 Environment_Engine: Remove Common_Engine reference
  Environment_Engine/Environment_Engine.csproj
  Environment_Engine/Query/Area.cs
Labels: type:compliance

#1733 Serialisation_Engine: Fix serialisation of objects with Id property
  Serialiser_Engine/Convert/Bson.cs
Labels: type:bug

#1743 Reflection_Engine: Non-generic treated as list when calling UnderlyingType()
  Reflection_Engine/Query/UnderlyingType.cs
Labels: type:bug, type:feature

#1753 ToRenderMesh() convert added for oM.Geometry.Mesh
  Graphics_Engine/Convert/ToRenderMesh.cs
  Graphics_Engine/Graphics_Engine.csproj
Labels: type:feature

#1769 Reflection_Engine: Enable creation of Generic methods and types from string
  Reflection_Engine/Compute/MakeGenericFromInputs.cs
  Reflection_Engine/Create/MethodBase.cs
  Reflection_Engine/Create/Type.cs
Labels: type:feature

#1789 Structure_Engine: Add create method for panel accepting a planar surface
  Structure_Engine/Create/Elements/Panel.cs
Labels: type:feature

#1792 Environment_Engine: Modify Space Object
  Environment_Engine/Create/Space.cs
Labels: type:feature

#1790 Structure_Engine: Adding comparer checking numbers for ICase objects
  Structure_Engine/Objects/EqualityComparers/CaseNumberComaprer.cs
  Structure_Engine/Structure_Engine.csproj
Labels: type:feature

#1799 Structure_Engine: Plastic modulus, SplitCurve removal of unneeded curve cast
  Structure_Engine/Compute/PlasticModulus.cs
Labels: type:bug

#1810 Environment_Engine: Align to BHoM for AnalysisGrid change
  Environment_Engine/Create/AnalysisGrid.cs
Labels: type:compliance

#1798 Data_Engine: ILogicalRequest.Requests query method implemented
  Data_Engine/Data_Engine.csproj
  Data_Engine/Query/Requests.cs
Labels: type:feature

#1815 Environment_Engine: Removed deprecated methods
  Environment_Engine/Modify/AddOpenings.cs
  Environment_Engine/Query/Level.cs
  Environment_Engine/Query/NormalAwayFromSpace.cs
  Environment_Engine/Query/PanelsByLevel.cs
  Environment_Engine/Query/PanelsByMaximumLevel.cs
  Environment_Engine/Query/PanelsByMinimumLevel.cs
  Environment_Engine/Query/PanelsContainingPoint.cs
  Environment_Engine/Query/StoreyGeometry.cs
Labels: type:compliance
