Repository BHoM/BHoM_Engine, pull requests merged in 2020-07, with the labels that each got.

#1872 Reflection_Engine: Making sure PropertyObjects also collects objets in list properties
  Reflection_Engine/Query/PropertyObjects.cs
Labels: type:bug

#1883 Diffing_Engine: Added Newtonsoft.json.dll in xcopy post build event
  Diffing_Engine/Diffing_Engine.csproj
Labels: type:compliance

#1894 Structure_Engine: Fix bug for default values for minimum cover for reinforcement layout
  Structure_Engine/Query/ReinforcementLayout.cs
Labels: type:bug

#1903 Spatial_Engine: ElementVerticies for IElement0D
  Spatial_Engine/Query/ElementVertices.cs
Labels: type:feature
