Repository BHoM/BHoM_Engine, pull requests merged in 2020-11, with the labels that each got.

#2120 BHoM_Engine: Correctly assign CustomObject properties like Name and Tags
  BHoM_Engine/Create/CustomObject.cs
Labels: type:bug

#2130 Environment_Engine: Tidy up clone methods
  Environment_Engine/Modify/Copy.cs
  Environment_Engine/Modify/FixNormal.cs
  Environment_Engine/Modify/RemoveOpening.cs
  Environment_Engine/Modify/RemoveOpeningsByName.cs
  Environment_Engine/Modify/SetGeometry.cs
  Environment_Engine/Modify/SetInternalElements2D.cs
  Environment_Engine/Modify/SetOutlineElements1D.cs
  Environment_Engine/Modify/Split.cs
  Environment_Engine/Modify/SplitOpeningByGeometry.cs
  Environment_Engine/Modify/SplitPanelByGeometry.cs
  Environment_Engine/Query/NewElement1D.cs
Labels: type:compliance

#2131 Tidy clone methods
  MEP_Engine/Modify/SetGeometry.cs
Labels: type:compliance

#2134 Spatial_Engine: Add fallback method to Query.IsNearGrid()
  Spatial_Engine/Query/IsNearGrid.cs
Labels: type:compliance

#2154 Spatial_Engine: Replace clone methods
  Spatial_Engine/Query/PointLayout.cs
Labels: size:XS, type:compliance

#2162 MEP_Engine: Remove unnecessary Create methods
  MEP_Engine/Create/CoolingCoil.cs
  MEP_Engine/Create/ElectricalConnector.cs
  MEP_Engine/Create/EnergyWheel.cs
  MEP_Engine/Create/Fan.cs
  MEP_Engine/Create/FanCoilUnit.cs
  MEP_Engine/Create/Filter.cs
  MEP_Engine/Create/GeometryFragment.cs
  MEP_Engine/Create/HeatingCoil.cs
  MEP_Engine/Create/IdentityFragment.cs
  MEP_Engine/MEP_Engine.csproj
Labels: type:compliance

#2142 Reflection_Engine: Make it easy to clear the value of a property
  Reflection_Engine/Modify/SetPropertyValue.cs
Labels: type:bug

#2159 Architecture_Engine: Replace clone calls with calls to DeepClone or ShallowClone
  Architecture_Engine/Create/Theatron/ProfileOrigin.cs
  Architecture_Engine/Create/Theatron/SeatingBlock.cs
  Architecture_Engine/Modify/CleanRoom.cs
  Architecture_Engine/Modify/SetGeometry.cs
  Architecture_Engine/Modify/SetOutlineElements1D.cs
  Architecture_Engine/Query/NewElement1D.cs
Labels: type:compliance

#2166 Environment_Engine: Add skipped regions to regionsNotMatched output
  Environment_Engine/Compute/MapRegions.cs
Labels: type:bug

#2174 Environment_Engine: Remove boolean input for ShallowClone
  Environment_Engine/Modify/Copy.cs
  Environment_Engine/Modify/RemoveOpening.cs
  Environment_Engine/Modify/RemoveOpeningsByName.cs
  Environment_Engine/Modify/SetGeometry.cs
  Environment_Engine/Modify/SplitOpeningByGeometry.cs
  Environment_Engine/Modify/SplitPanelByGeometry.cs
  MEP_Engine/Modify/SetGeometry.cs
Labels: type:compliance

#2163 Reflection_Engine: Update fallback method for ToText
  Reflection_Engine/Convert/ToText.cs
Labels: type:feature

#2191 Physical_Engine: TopCentreline and BottomCentreline fixed to return correct curves
  Physical_Engine/Query/BottomCentreline.cs
  Physical_Engine/Query/TopCentreline.cs
Labels: type:bug

#2186 Physical_Engine: Add query method moving location line to the centre of the IFramingElement's section bounding box
  Physical_Engine/Physical_Engine.csproj
  Physical_Engine/Query/BoundingBoxCentreline.cs
Labels: type:feature

#2195 Reflection_Engine: Fix Enum display in UI
  Reflection_Engine/Convert/ToText.cs
Labels: severity:critical, type:bug

#2197 Serialiser_Engine: Treat ReadOnlyDictionary as Dictionary in Convention
  Serialiser_Engine/Objects/MemberMapConventions/BHoMDictionaryConvention.cs
Labels: type:bug

#2192 Geometry_Engine: Adding descriptions to the Normal() methods
  Geometry_Engine/Query/Normal.cs
  Spatial_Engine/Query/Normal.cs
Labels: type:documentation

#2188 Physical_Engine: ExplicitBulk required extension methods added
  Physical_Engine/Query/MaterialComposition.cs
  Physical_Engine/Query/SolidVolume.cs
Labels: type:feature
