Repository BHoM/BHoM_Engine, pull requests merged in 2020-06, with the labels that each got.

#1825 Common_Engine: Remove ConstructionPhase Create method
  Common_Engine/Common_Engine.csproj
  Common_Engine/Create/ConstructionPhase.cs
Labels: type:compliance

#1811 Serialiser_Engine: Fix issue serialising Immutable objects with properties overridden from base class.
  Serialiser_Engine/Objects/MemberMapConventions/ImmutableBHoMClassMapConvention.cs
Labels: type:bug

#1829 Structure_Results_Engine: Aligning with changes for migrating results to Analytical_oM
  Results_Engine/Query/Group.cs
  Results_Engine/Results_Engine.csproj
  Structure_Engine/Create/Elements/IElement1D/NewElement1D.cs
  Structure_Engine/Query/SelectCase.cs
  Structure_Engine/Structure_Engine.csproj
Labels: type:external-api-changes

#1839 Structure_Engine: Fixed bug where deprecated method did not implement new method for FabricatedISectionProfile
  Structure_Engine/Create/SectionProperties/SectionProfile.cs
Labels: severity:medium, size:S, type:bug

#1837 Structure_Engine: Add support for NodeModalMass for converting Request
  Structure_Engine/Create/Requests/IResultRequest.cs
Labels: type:feature

#1842 Geometry_Engine: Fix edgecase for Create PlanarSurface
  Geometry_Engine/Create/PlanarSurface.cs
Labels: type:bug

#1844 Geometry_Engine: null checks in Bounds
  Geometry_Engine/Query/Bounds.cs
Labels: type:bug

#1846 Geometry_Engine: Fix IsSelfIntersecting
  Geometry_Engine/Query/IsSelfIntersecting.cs
Labels: type:bug

#1852 Serialiser_Engine: Fixing member mapping for Immutable inheriting from non-abstract class
  Serialiser_Engine/Compute/RegisterClassMap.cs
  Serialiser_Engine/Objects/MemberMapConventions/ImmutableBHoMClassMapConvention.cs
Labels: type:bug

#1854 Structure_Engine: Allow Query.Geometry to return invalid PlanarSurfaces for the case of invalid Structure.Panels
  Structure_Engine/Query/Geometry.cs
Labels: type:bug

#1855 Environment_Engine: Remove unit conversions
  Environment_Engine/Compute/SolarPosition.cs
  Environment_Engine/Convert/Degrees.cs
Labels: type:compliance

#1843 Geometry_Engine: Better handling of corner cases in IsContaining
  Geometry_Engine/Query/IsContaining.cs
Labels: type:bug

#1859 Structure_Engine: Adding simple create methods for result requests
  Structure_Engine/Create/Requests/BarResultRequest.cs
  Structure_Engine/Create/Requests/GlobalResultRequest.cs
  Structure_Engine/Create/Requests/MeshResultRequest.cs
  Structure_Engine/Create/Requests/NodeResultRequest.cs
  Structure_Engine/Structure_Engine.csproj
Labels: type:compliance

#1861 Environment_Engine: Migrate code from IES_Toolkit
  Environment_Engine/Environment_Engine.csproj
  Environment_Engine/Query/BottomLeft.cs
  Environment_Engine/Query/BottomRight.cs
  Environment_Engine/Query/IsLeft.cs
  Environment_Engine/Query/TopRight.cs
Labels: type:compliance

#1857 Store previously run extension methods in a thread safe dictionary
  Reflection_Engine/Compute/RunExtensionMethod.cs
Labels: type:bug
