Repository BHoM/BHoM_Engine, pull requests merged in 2020-12, with the labels that each got.

#2182 Physical_Engine: IElementM required extension methods
  Physical_Engine/Physical_Engine.csproj
  Physical_Engine/Query/Mass.cs
  Physical_Engine/Query/MaterialComposition.cs
  Physical_Engine/Query/SolidVolume.cs
Labels: type:feature

#2204 Structure_Engine: Remove whitespace in Bar create method
  Structure_Engine/Create/Elements/Bar.cs
Labels: type:compliance

#2205 MEP_Engine: Matter-based workflows required extension methods
  MEP_Engine/Create/Elements/CableTraySectionProperty.cs
  MEP_Engine/Create/Elements/DuctSectionProperty.cs
  MEP_Engine/Create/Elements/PipeSectionProperty.cs
  MEP_Engine/Create/Elements/WireSectionProperty.cs
  MEP_Engine/MEP_Engine.csproj
  MEP_Engine/Query/MaterialComposition.cs
  MEP_Engine/Query/SolidVolume.cs
Labels: type:compliance, type:feature

#2212 BHoM_Enigne: Remove duplicate FindFragment method
  BHoM_Engine/Query/FindFragment.cs
Labels: severity:critical, type:bug

#2210 Spatial_Engine: Add option to centre FreeFormProfiles
  Spatial_Engine/Create/ShapeProfiles/FreeFormProfile.cs
Labels: type:feature

#2216 Facade_Engine: Fixed dictionary bug for adjacency check
  Facade_Engine/Compute/UniqueAdjacencies.cs
  Facade_Engine/Query/IsAdjacent.cs
Labels: type:bug

#2218 Reflection_Engine: Adding ability to remove events from log
  Reflection_Engine/Compute/RemoveEvent.cs
  Reflection_Engine/Reflection_Engine.csproj
Labels: type:bug

#2224 BHoM_Engine: Query.Hash() to return a Hash also when an object with all empty or null properties is input
  BHoM_Engine/Query/Hash.cs
Labels: severity:critical, size:S

#2220 Geometry_Engine: Add null check to Area(pSurf)
  Geometry_Engine/Query/Area.cs
Labels: type:bug

#2227 Reflection_Engine: Fix Adapter list to include adapters that don't inherit directly from BHoM_Adapter
  Reflection_Engine/Query/TypeList.cs
Labels: type:bug

#2239 Facade_Engine: Adjacency check bugfix for matching edges
  Facade_Engine/Compute/EdgeAdjacencies.cs
  Facade_Engine/Query/IsAdjacent.cs
Labels: type:bug

#2241 Serialiser_Engine: Roll back counter from Deprecated serialiser
  Serialiser_Engine/Objects/BsonSerializers/DeprecatedSerializer.cs
Labels: severity:critical, type:bug

#2243 Serialiser_Engine: check if FullName is empty before returning Error in TypeSerializer
  Serialiser_Engine/Objects/BsonSerializers/TypeSerializer.cs
Labels: type:bug
