Repository BHoM/BHoM_Engine, pull requests merged in 2020-09, with the labels that each got.

#1961 Environment_Engine: Fix panel type setting bug
  Environment_Engine/Modify/SetFloorPanels.cs
  Environment_Engine/Modify/SetWallPanels.cs
Labels: type:bug

#1960 Geometry_Engine: implementing DiscontinuityPoints(PolyCurve) and adding tolerances to inputs
  Geometry_Engine/Query/DiscontinuityPoints.cs
Labels: severity:low, size:S, type:compliance, type:feature

#1966 Structure_Engine: Update to area loads visualisation
  Structure_Engine/Query/PointGrid.cs
  Structure_Engine/Query/Visualize.cs
Labels: type:bug, type:feature

#1969 Geometry_Engine: Clear not implemented create methods for NurbsCurve and NurbsSurface
  Geometry_Engine/Create/NurbsCurve.cs
  Geometry_Engine/Create/NurbsSurface.cs
Labels: severity:low, size:XS

#1972 Geometry_Engine: Add IsEqual(NurbsCurve)
  Geometry_Engine/Query/IsEqual.cs
Labels: severity:low, size:S, type:feature

#1984 Geometry_Engine: Adding more sample points to IsClockwise
  Geometry_Engine/Query/IsClockwise.cs
Labels: type:bug

#1985 Structure_Engine: Update Torsional constant calculation for BoxProfiles
  Structure_Engine/Query/TorsionalConstant.cs
Labels: type:feature

#1992 Reflection_Engine: Fix ExtractAllAsemblies bug
  Reflection_Engine/Query/AssemblyList.cs
Labels: type:bug

#1996 Physical_Engine: Removing reference to Common_oM
  Physical_Engine/Physical_Engine.csproj
Labels: type:compliance

#2000 Environment_Engine: Fix bug in MapToLevels
  Environment_Engine/Compute/MapToLevel.cs
Labels: type:bug

#2002 Reflection_Engine: Record message when failing to load methods
  Reflection_Engine/Query/MethodList.cs
Labels: type:compliance
