Repository BHoM/BHoM_Engine, pull requests merged in 2020-03, with the labels that each got.

#1535 Serialiser_Engine: Compliance Update
  Serialiser_Engine/Compute/AllowUpgradeFromBson.cs
  Serialiser_Engine/Serialiser_Engine.csproj
Labels: type:compliance

#1532 MEP_Engine: Compliance Update
  MEP_Engine/Create/AirHandlingUnit.cs
Labels: type:compliance

#1540 Geometry_Engine: Compliance Update
  Geometry_Engine/Modify/Offset.cs
Labels: type:compliance

#1524 Acoustic_Engine: Compliance Update
  Acoustic_Engine/Acoustic_Engine.csproj
  Acoustic_Engine/Query/Rasti.cs
Labels: type:compliance

#1528 Data_Engine: Compliance Update
  Data_Engine/Data_Engine.csproj
  Data_Engine/Query/FirstValueAbove.cs
  Data_Engine/Query/FirstValueAt.cs
  Data_Engine/Query/ValuesAbove.cs
  Data_Engine/Query/ValuesAt.cs
Labels: type:compliance

#1493 Reflection_Engine: null check for `ExtractAllTypes()` to avoid attempting collection of anonymous types
  Reflection_Engine/Query/TypeList.cs
Labels: type:bug

#1542 Serialiser_Engine: Fix bug for deserialisation of List<IBHoMObject> containing CustomObjects
  Serialiser_Engine/Convert/Bson.cs
  Serialiser_Engine/Objects/MemberMapConventions/BHoMObjectDiscriminatorConvention.cs
  Serialiser_Engine/Serialiser_Engine.csproj
Labels: type:bug

#1505 Geometry_Engine: Allow equal values for shape profiles
  Geometry_Engine/Create/ShapeProfile.cs
Labels: type:bug

#1546 Environment_Engine: Fix scope
  Environment_Engine/Query/CullDuplicateLines.cs
Labels: type:compliance

#1549 Versioning_Engine: Functionality for multiple instances of Rhino (or any UI)
  Versioning_Engine/Convert/ToNewVersion.cs
Labels: type:bug

#1557 Environment_Engine: Add query for FrameFactor
  Environment_Engine/Environment_Engine.csproj
  Environment_Engine/Query/FrameFactor.cs
Labels: type:feature

#1560 Environment_Engine: Add compute to extrude Architecture Rooms into closed volumes
  Environment_Engine/Compute/ExtrudeToVolume.cs
  Environment_Engine/Environment_Engine.csproj
Labels: type:feature

#1566 Environment_Engine: Align to oM changes
  Environment_Engine/Create/Space.cs
Labels: type:external-api-changes

#1551 Geometry_Engine: remove the ClipPolylines method
  Geometry_Engine/Compute/ClipPolylines.cs
  Geometry_Engine/Geometry_Engine.csproj
  Humans_Engine/Query/AvalueAnalysis.cs
Labels: severity:low, size:S, type:compliance

#1576 BHoM_Engine: Update CI files
  .ci/check-all-depandants.yml
  .ci/check-core.yml
  .ci/check-installer.yml
  .ci/run-compliance-tests.yml
Labels: type:compliance

#1574 Environment_Engine: Add compute method for mapping rooms to levels
  Environment_Engine/Compute/MapToLevel.cs
  Environment_Engine/Environment_Engine.csproj
Labels: type:feature

#1580 Structure_Engine: Fix inconsistency in naming between property and create method arguments
  Structure_Engine/Create/Loads/GravityLoad.cs
  Structure_Engine/Create/Loads/PointVelocity.cs
Labels: type:documentation

#1581 Library_Engine: Only pick up exact path for library search strings once
  Library_Engine/Query/Datasets.cs
  Library_Engine/Query/Libraries.cs
  Library_Engine/Query/RefreshLibraries.cs
Labels: type:bug

#1586 Reflection_Engine: Extract descriptions of enum options
  Reflection_Engine/Query/Description.cs
Labels: type:documentation

#1597 Matter_Engine: Update CODEOWNERS
  .github/CODEOWNERS
Labels: type:compliance

#1603 Geometry_Engine: Add last control point for Simplify
  Geometry_Engine/Modify/Simplify.cs
Labels: type:bug

#1600 Environment_Engine: Fix wall edges of ExtrudeToVolume
  Environment_Engine/Compute/ExtrudeToVolume.cs
Labels: type:bug

#1579 Reflection_Engine: Added set property functionality for custom data
  Reflection_Engine/Modify/SetPropertyValue.cs
Labels: type:bug

#1598 Environment_Engine: Sort Outputs based on Level in MapToLevel
  Environment_Engine/Compute/MapToLevel.cs
Labels: type:bug

#1605 Environment_Engine: ExtrudeToVolume for polyline
  Environment_Engine/Compute/ExtrudeToVolume.cs
Labels: type:bug

#1607 Library_Engine: Fix type in SourceAndDisclaimer when no source is available
  Library_Engine/Query/SourceAndDisclaimer.cs
Labels: size:XS, type:bug, type:documentation

#1619 Serialiser_Engine: Fix deserialisation of string when top object
  Serialiser_Engine/Convert/Bson.cs
Labels: type:bug
