Repository BHoM/BHoM_Engine, pull requests merged in 2020-02, with the labels that each got.

#1445 Units_Engine : Removal of Units_Engine
  BHoM_Engine.sln
  Units_Engine/Properties/AssemblyInfo.cs
  Units_Engine/Units_Engine.csproj
  Units_Engine/Units_Engine.nuspec
Labels: type:compliance

#1443 Environment_Engine: Fix bug in copy panel for null fragment set
  Environment_Engine/Modify/Copy.cs
Labels: severity:critical, type:bug

#1413 Reflection_Engine: Adding quantity notes to MemberInfo description
  Reflection_Engine/Query/Description.cs
  Reflection_Engine/Reflection_Engine.csproj
Labels: type:feature

#1452 Update CI checking file
  .ci/CloneTest.ps1
Labels: status:WIP, type:bug, type:compliance

#1454 BHoM_Engine: Update CI file to check if path already exists
  .ci/CloneTest.ps1
Labels: type:bug, type:compliance

#1456 BHoM_Engine: Update CI file
  .ci/CloneTest.ps1
Labels: type:bug

#1449 Data_Engine: Add attribute dictionary to GraphNode and GraphLink
  Data_Engine/Create/GraphLink.cs
  Data_Engine/Create/GraphNode.cs
Labels: severity:low, size:S

#1457 BHoM_Engine: Update CI for upstream breaking changes
  .ci/CloneTest.ps1
Labels: type:bug, type:compliance

#1463 Reflection_Engine: Extracting descriptions of properties for Create methods
  Reflection_Engine/Query/Description.cs
Labels: type:feature

#1477 Versioning_Engine - Add support for versioning chains
  Versioning_Engine/Convert/ToNewVersion.cs
Labels: type:feature

#1486 BHoM_Engine: RemoveFragment returns the same BHoMObject if the given fragment is not found
  BHoM_Engine/Modify/RemoveFragment.cs
Labels: size:XS, type:feature

#1491 Structure_Engine: Plastic modulus, SplitAtX fix
  Structure_Engine/Compute/PlasticModulus.cs
Labels: type:bug

#1495 BHoM_Engine: Rename IBHoMFragment -> IFragment
  BHoM_Engine/Create/RandomObject.cs
  BHoM_Engine/Modify/AddFragment.cs
  BHoM_Engine/Modify/RemoveFragment.cs
  BHoM_Engine/Query/FindFragment.cs
  BHoM_Engine/Query/GetAllFragments.cs
  Environment_Engine/Modify/AddFragment.cs
Labels: type:compliance

#1497 Environment_Engine: Deprecate Add Fragment method
  Environment_Engine/Modify/AddFragment.cs
Labels: type:compliance

#1499 Structure_Engine: Split FeMesh.Geometry() into three methods
  Structure_Engine/Query/Geometry.cs
Labels: type:compliance
