Repository BHoM/BHoM_Engine, pull requests merged in 2020-04, with the labels that each got.

#1628 Geometry_Engine: Area for PlanarSurface and PolySurface
  Geometry_Engine/Query/Area.cs
Labels: type:feature

#1655 Reflection_Engine: Migrate Dummy and IsEqual methods to the Test Toolkit
  Reflection_Engine/Compute/DummyObject.cs
  Reflection_Engine/Query/IsEqual.cs
  Reflection_Engine/Reflection_Engine.csproj
  Reflection_Engine/packages.config
Labels: type:bug

#1647 Physical_Engine: Correct area for SolidVolume
  Physical_Engine/Query/SolidVolume.cs
Labels: type:bug

#1632 Geometry_Engine: Clarify input naming in CollapseToScaledPolyline.cs
  Geometry_Engine/Compute/CollapseToScaledPolyline.cs
Labels: type:compliance

#1630 Spatial_Engine: Add HasMergeablePropertiesWith method
  Spatial_Engine/Query/HasMergeablePropertiesWith.cs
  Spatial_Engine/Spatial_Engine.csproj
Labels: type:feature

#1667 Environments_Engine: Updated Engine Method for Create Gain
  Environment_Engine/Create/Gains.cs
Labels: type:external-api-changes

#1670 Structure_Engine: Create Section from TaperedProfile fix
  Structure_Engine/Compute/Integrate.cs
  Structure_Engine/Compute/IntegrateSection.cs
Labels: type:bug

#1668 Reflection_Engine: Update IsDeprecated method
  Reflection_Engine/Query/IsDeprecated.cs
Labels: type:feature

#1685 Reflection_Engine: Remove boilerplate default descriptions
  Reflection_Engine/Query/Description.cs
Labels: type:feature

#1689 Structure_Engine: Adding comparers for Contraints4DOF and 6DOF from Robot_Toolkit
  Structure_Engine/Objects/EqualityComparers/Constraint4DOFComparer.cs
  Structure_Engine/Objects/EqualityComparers/Constraint6DOFComparer.cs
  Structure_Engine/Structure_Engine.csproj
Labels: type:feature

#1691 Environment_Engine: Add UniqueConstructions for Openings
  Environment_Engine/Query/UniqueConstructions.cs
Labels: type:feature

#1696 Serialiser_Engine: Fix issue of failing to deserialise methods if multiple engine method matches are found
  Reflection_Engine/Create/Type.cs
  Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs
Labels: type:bug

#1714 Spatial_Engine: Add RoundCoordinates
  Spatial_Engine/Modify/RoundCoordinates.cs
  Spatial_Engine/Spatial_Engine.csproj
Labels: type:feature

#1716 Library_Engine: Warning added when the library under given name is not found in the folder
  Library_Engine/Query/Datasets.cs
Labels: type:bug
