Repository BHoM/BHoM_Engine, pull requests merged in 2020-10, with the labels that each got.

#2018 Spatial_Engine: ElementVertices fixed to return actual vertices
  Spatial_Engine/Query/ElementVertices.cs
Labels: type:bug

#2022 Geometry_Engine: Using explicit casting in Offset to avoid losing cPts while passing arguments to Polyline method
  Geometry_Engine/Modify/Offset.cs
Labels: size:S, type:bug

#2027 Environment_Engine: Add map to space method
  Environment_Engine/Compute/MapSpaces.cs
  Environment_Engine/Environment_Engine.csproj
Labels: type:feature

#2051 Reflection_Engine: Make sure outputs always have different names
  Reflection_Engine/Query/OutputAttributes.cs
Labels: type:bug

#2045 Geometry Engine: PointAtParameter(Polyline) sometimes returns null on parameter equal 1.0
  Geometry_Engine/Query/PointAtParameter.cs
Labels: severity:critical, size:S, type:bug

#2057 Reflection_Engine: Adding attributes to better control auto-create components
  Reflection_Engine/Query/DefaultValueWarning.cs
  Reflection_Engine/Query/IsAutoConstructorAllowed.cs
  Reflection_Engine/Query/IsRequired.cs
  Reflection_Engine/Reflection_Engine.csproj
Labels: type:feature

#2058 Geometry_Engine: Update Transform BoundaryRepresentation to handle Volume Property
  Geometry_Engine/Modify/Transform.cs
Labels: type:feature

#2059 Programming_Engine: Migrate code from constructor of NodeBlock and LoopBlock to new Create methods
  Programming_Engine/Create/BlockNode.cs
  Programming_Engine/Create/LoopNode.cs
  Programming_Engine/Programming_Engine.csproj
Labels: type:compliance

#2066 Reflection_Engine: Remove calls to Clone methods and Clean SetProperty methods
  Reflection_Engine/Modify/SetPropertyValue.cs
Labels: type:compliance

#2082 Spatial_Engine: Explicit use of geometry engine in Area(IElement2D)
  Spatial_Engine/Query/Area.cs
Labels: type:bug

#2084 Geometry_Engine: Adding null checks for IsVertical
  Geometry_Engine/Query/IsVertical.cs
Labels: type:bug, type:compliance

#2087 Spatial_Engine: Updating Area calls to Geometry_Engine instead of Spatial_Engine
  Spatial_Engine/Compute/DistributeOutlines.cs
  Spatial_Engine/Create/ShapeProfiles/FreeFormProfile.cs
  Spatial_Engine/Query/PointLayout.cs
Labels: severity:critical, type:bug

#2089 Reflection_Engine: Adding nullchecks for lists in DistinctProperties
  Reflection_Engine/Query/DistinctProperties.cs
Labels: type:bug

#2070 Geometry_Engine: Replace calls to Clone, IClone, and GetShallowClone methods with calls to DeepClone and ShallowClone
  Geometry_Engine/Compute/BooleanDifference.cs
  Geometry_Engine/Compute/BooleanIntersection.cs
  Geometry_Engine/Compute/BooleanUnion.cs
  Geometry_Engine/Compute/ClusterCollinear.cs
  Geometry_Engine/Compute/DistributeOutlines.cs
  Geometry_Engine/Compute/RowEchelonForm.cs
  Geometry_Engine/Compute/SortAlongCurve.cs
  Geometry_Engine/Compute/SortCollinear.cs
  Geometry_Engine/Compute/WetBlanketInterpretation.cs
  Geometry_Engine/Convert/NurbsForm.cs
  Geometry_Engine/Create/Plane.cs
  Geometry_Engine/Geometry_Engine.csproj
  Geometry_Engine/Modify/CollapseToPolyline.cs
  Geometry_Engine/Modify/Flip.cs
  Geometry_Engine/Modify/MergeVertices.cs
  Geometry_Engine/Modify/Mirror.cs
  Geometry_Engine/Modify/Normalise.cs
  Geometry_Engine/Modify/Offset.cs
  Geometry_Engine/Modify/Project.cs
  Geometry_Engine/Modify/ProjectAlong.cs
  Geometry_Engine/Modify/SetGeometry.cs
  Geometry_Engine/Modify/SortCurves.cs
  Geometry_Engine/Modify/SplitAtPoints.cs
  Geometry_Engine/Modify/Transform.cs
  Geometry_Engine/Modify/Translate.cs
  Geometry_Engine/Query/Area.cs
  Geometry_Engine/Query/Bounds.cs
  Geometry_Engine/Query/Clone.cs
  Geometry_Engine/Query/ExternalEdges.cs
  Geometry_Engine/Query/InternalEdges.cs
  Geometry_Engine/Query/IsClockwise.cs
  Geometry_Engine/Query/IsCoplanar.cs
  Geometry_Engine/Query/LineIntersections.cs
Labels: type:compliance

#2091 Environment_Engine: Add ability to group openings and panels by their type
  Environment_Engine/Environment_Engine.csproj
  Environment_Engine/Query/Group.cs
Labels: type:feature

#2062 Reflection_Engine: StoreAllMethods() to catch exception on individual method
  Reflection_Engine/Query/MethodList.cs
Labels: type:feature

#2098 Reflection_Engine: Extraction of MemberInfo/ParameterInfo description without type description enabled
  Reflection_Engine/Query/Description.cs
Labels: type:feature

#2093 Spatial_Engine: Add Query.IsNearGrid() method
  Spatial_Engine/Query/IsNearGrid.cs
  Spatial_Engine/Spatial_Engine.csproj
Labels: type:feature

#2107 BHoM_Engine: Added global & property-specific fractional precision in `Query.Hash()`
  BHoM_Engine/BHoM_Engine.csproj
  BHoM_Engine/Query/Hash.cs
Labels: type:feature

#2108 MEP_Engine: Remove CustomData
  MEP_Engine/MEP_Engine.csproj
  MEP_Engine/Query/EquipmentLengthByPart.cs
Labels: type:compliance

#2114 Data_Engine: Remove custom data
  Data_Engine/Query/Linq/FilterBy.cs
Labels: type:compliance
