Repository BHoM/BHoM_Engine, pull requests merged in 2020-01, with the labels that each got.

#1395 BHoM_Engine: Update assembly file version
  Acoustic_Engine/Properties/AssemblyInfo.cs
  Analytical_Engine/Properties/AssemblyInfo.cs
  Architecture_Engine/Properties/AssemblyInfo.cs
  BHoM_Engine/Properties/AssemblyInfo.cs
  Common_Engine/Properties/AssemblyInfo.cs
  Data_Engine/Properties/AssemblyInfo.cs
  Diffing_Engine/Properties/AssemblyInfo.cs
  Environment_Engine/Properties/AssemblyInfo.cs
  Geometry_Engine/Properties/AssemblyInfo.cs
  Graphics_Engine/Properties/AssemblyInfo.cs
  Humans_Engine/Properties/AssemblyInfo.cs
  Library_Engine/Properties/AssemblyInfo.cs
  MEP_Engine/Properties/AssemblyInfo.cs
  Physical_Engine/Properties/AssemblyInfo.cs
  Planning_Engine/Properties/AssemblyInfo.cs
  Reflection_Engine/Properties/AssemblyInfo.cs
  Results_Engine/Properties/AssemblyInfo.cs
  Serialiser_Engine/Properties/AssemblyInfo.cs
  Speech_Engine/Properties/AssemblyInfo.cs
  Structure_Engine/Properties/AssemblyInfo.cs
  Units_Engine/Properties/AssemblyInfo.cs
  Versioning_Engine/Properties/AssemblyInfo.cs
Labels: type:compliance

#1403 Geometry_Engine: added white space for compliance
  Geometry_Engine/Create/ShapeProfileCurves.cs
Labels: severity:low, size:XS, type:compliance

#1352 Geometry_Engine: Add constructor for TaperedProfile
  Geometry_Engine/Create/ShapeProfile.cs
Labels: severity:medium, size:S, type:feature

#1417 Environment_Engine: Add ability to Offset Openings
  Environment_Engine/Environment_Engine.csproj
  Environment_Engine/Modify/OffsetOpenings.cs
Labels: type:feature

#1420 BHoM_Engine: Instantiating new FragmentSet in ShallowClone method
  BHoM_Engine/Query/ShallowClone.cs
Labels: type:feature

#1408 Geometry Engine: fix Offset(PolyCurve) Arcs bug
  Geometry_Engine/Modify/Offset.cs
Labels: severity:medium, size:XS, type:bug

#1432 Environment_Engine: Add flag for unique construction names
  Environment_Engine/Query/UniqueConstructions.cs
Labels: type:feature

#1426 Library_Engine: Added partial match method
  Library_Engine/Query/Match.cs
Labels: size:S, type:feature

#1437 Reflection_Engine: Add null check for UnderlyingType method
  Reflection_Engine/Query/UnderlyingType.cs
Labels: type:bug

#1441 Environment_Engine: SetRoofPanels to set ceilings and internalfloor between spaces
  Environment_Engine/Modify/SetPanelType.cs
Labels: type:bug
