Repository BHoM/BHoM_Engine, pull requests merged in 2021-03, with the labels that each got.

#2367 Reflection_Engine: Fix bug on method with nested generic inputs called from the UI
  Reflection_Engine/Compute/MakeGenericFromInputs.cs
Labels: type:bug, type:feature

#2374 Physical engine: adding geometry3D method for Physical Floor
  Physical_Engine/Query/Geometry3D.cs
Labels: type:feature

#2378 Reflection_Engine: Null method message introduced in RunExtensionMethod commented out temporarily
  Reflection_Engine/Compute/RunExtensionMethod.cs
Labels: type:bug

#2385 Data_Engine: Requests method moved to Query class
  Data_Engine/Query/Requests.cs
Labels: type:compliance

#2394 Humans_Engine: Add previous version attribute to CvalueAnalysis
  Humans_Engine/Query/CvalueAnalysis.cs
Labels: type:compliance

#2395 Geometry_Engine: Adding proper rigidness check to the Transform methods
  Geometry_Engine/Modify/Transform.cs
Labels: type:bug

#2402 Reflection_Engine: InheritedTypes stopped from passing nulls to output
  Reflection_Engine/Query/InheritedTypes.cs
Labels: type:bug

#2404 Facade_Engine: Added null FrameEdgeProperty handling and improved warnings and errors
  Facade_Engine/Query/FrameGeometry2D.cs
  Facade_Engine/Query/SolidVolume.cs
  Facade_Engine/Query/WidthIntoOpening.cs
Labels: type:bug

#2407 Geometry_Engine: Infinite loop removed from Split in case of overlapping cutting lines
  Geometry_Engine/Compute/Split.cs
Labels: type:bug
