Repository BHoM/BHoM_Engine, pull requests merged in 2021-04, with the labels that each got.

#2432 Geometry_Engine: point on plane projection fixed
  Geometry_Engine/Modify/Project.cs
Labels: type:bug

#2436 BHoM_Engine: Fix FilterByType
  BHoM_Engine/Query/FilterByType.cs
Labels: type:bug

#2437 Base_Engine: Create a useable DateTime for RandomObject
  BHoM_Engine/Create/IObject/RandomObject.cs
Labels: type:bug

#2421 Reflection_Engine: Make sure no warning is shown when setting property of a CustomObject
  Reflection_Engine/Modify/SetPropertyValue.cs
Labels: type:bug

#2422 Serialiser_Engine: Fix serialisation of Dictionary as top level object
  Serialiser_Engine/Convert/Json.cs
Labels: type:bug

#2453 Serialiser_Engine: RegisterClassMaps added for entire assemblies
  Serialiser_Engine/Compute/RegisterClassMap.cs
  Serialiser_Engine/Convert/Bson.cs
Labels: type:feature

#2456 Serialisation_Engine: Fix Serialisation of Generics
  Serialiser_Engine/Compute/RegisterClassMap.cs
Labels: severity:critical, type:bug

#2484 Library_Engine: Handle nulls
  Library_Engine/Convert/ToText.cs
Labels: type:compliance

#2476 BHoM_Engine: Handle nulls
  BHoM_Engine/Query/Geometry.cs
  BHoM_Engine/Query/Geometry3D.cs
  BHoM_Engine/Query/GetAllFragments.cs
  BHoM_Engine/Query/Hash.cs
  BHoM_Engine/Query/UniquenessRestrictions.cs
Labels: type:compliance

#2488 Environment_Engine: Fix typo in method name + versioning for method as appropriate
  Environment_Engine/Modify/SetAdjacentSpaces.cs
Labels: type:bug

#2457 Reflection_Engine: Add support for setting an enum property from a string
  Reflection_Engine/Modify/SetPropertyValue.cs
Labels: type:feature

#2469 Diffing_Engine: Handle nulls
  Diffing_Engine/Compute/DiffRevisions.cs
  Diffing_Engine/Convert/TryParseObjectToGuid.cs
  Diffing_Engine/Create/Delta.cs
  Diffing_Engine/Create/Revision.cs
  Diffing_Engine/Query/RevisionFragment.cs
Labels: type:compliance

#2471 Acoustic_Engine: Handle nulls
  Acoustic_Engine/Acoustic_Engine.csproj
  Acoustic_Engine/Create/Ray.cs
  Acoustic_Engine/Query/GainFactor.cs
  Acoustic_Engine/Query/Length.cs
  Acoustic_Engine/Query/Order.cs
  Acoustic_Engine/Query/Plane.cs
  Acoustic_Engine/Query/ReverbDistance.cs
  Acoustic_Engine/Query/SabineTime.cs
  Acoustic_Engine/Query/SoundLevel.cs
  Acoustic_Engine/Query/TimeConstant.cs
  Acoustic_Engine/Query/TravelTime.cs
Labels: type:compliance

#2482 Humans_Engine: Handle nulls
  Humans_Engine/Create/Spectator.cs
  Humans_Engine/Humans_Engine.csproj
  Humans_Engine/Query/AvalueAnalysis.cs
  Humans_Engine/Query/CvalueAnalysis.cs
  Humans_Engine/Query/EvalueAnalysis.cs
  Humans_Engine/Query/TrackingLines.cs
Labels: type:compliance

#2480 Graphics_Engine: Handle nulls
  Graphics_Engine/Convert/ToRenderMesh.cs
  Graphics_Engine/Convert/ToSVGString.cs
  Graphics_Engine/Create/Marker.cs
  Graphics_Engine/Modify/RepresentationFragments/Boxes.cs
  Graphics_Engine/Modify/View/DependencyChart.cs
  Graphics_Engine/Modify/View/View.cs
  Graphics_Engine/Query/Bounds.cs
  Graphics_Engine/Query/Color.cs
  Graphics_Engine/Query/IsNumericType.cs
  Graphics_Engine/Query/Scales/Scale.cs
Labels: type:compliance

#2478 Facade_Engine: Handle nulls
  Facade_Engine/Create/Elements/Opening.cs
  Facade_Engine/Create/Elements/Panel.cs
  Facade_Engine/Query/Depth.cs
  Facade_Engine/Query/IsAdjacent.cs
  Facade_Engine/Query/MaterialComposition.cs
  Facade_Engine/Query/PrimaryPropertyName.cs
  Facade_Engine/Query/SimpleGeometry.cs
  Facade_Engine/Query/SolidVolume.cs
  Facade_Engine/Query/Width.cs
Labels: type:compliance
