Repository BHoM/BHoM_Engine, pull requests merged in 2021-09, with the labels that each got.

#2608 Geometry_Engine: Planar surface creation without openings fixed
  Geometry_Engine/Create/PlanarSurface.cs
Labels: type:bug

#2611 Structure_Engine: rename DOF f to o
  Structure_Engine/Query/Description.cs
Labels: type:documentation

#2615 Reflection_Engine: Add ability to set Fragment property from list of objects
  Reflection_Engine/Modify/SetPropertyValue.cs
Labels: type:bug

#2622 Geometry_Engine: planar surface creation and DistributeOutlines checks/messages refined
  Geometry_Engine/Create/PlanarSurface.cs
Labels: type:bug, type:compliance

#2625 Graphics_Engine: added new RenderMesh extension method
  Graphics_Engine/Graphics_Engine.csproj
  Graphics_Engine/Query/RenderMesh.cs
Labels: type:feature
