Repository BHoM/BHoM_Engine, pull requests merged in 2021-01, with the labels that each got.

#2256 Geometry_Engine: Correcting logged events in Centroid methods
  Geometry_Engine/Query/Centroid.cs
Labels: type:compliance

#2124 Reflection_Engine: Adding check for Fragments in the DistinctProperties
  Reflection_Engine/Query/DistinctProperties.cs
Labels: type:feature

#2259 Reflection_Engine: Remove the condition that BHoMTypeList can only contain IObjects
  Reflection_Engine/Query/TypeList.cs
Labels: severity:critical, type:bug

#2178 Serialiser_Engine: add support for Json Arrays
  Serialiser_Engine/Convert/Json.cs
Labels: type:feature

#2265 CI/CD: Update core.txt for CheckCore
  core.txt
Labels: type:compliance

#2281 Reflection_Engine: Fix SetProperty of CustomData
  Reflection_Engine/Modify/SetPropertyValue.cs
Labels: type:bug

#2286 Programming_Engine: Remove ParentId property from INodeParam
  Programming_Engine/Create/BlockNode.cs
  Programming_Engine/Create/LoopNode.cs
Labels: type:compliance
