Repository BHoM/BHoM_Engine, pull requests merged in 2021-02, with the labels that each got.

#2290 Serialiser_Engine: Get all methods, objects, and type to serialise
  Serialiser_Engine/Convert/Bson.cs
  Serialiser_Engine/Convert/Json.cs
  Serialiser_Engine/Objects/BsonSerializers/BHoMCollectionSerializer.cs
  Serialiser_Engine/Objects/BsonSerializers/TypeSerializer.cs
  Serialiser_Engine/Serialiser_Engine.csproj
Labels: type:compliance

#2312 Reflection_Engine: Make the RecordEvent(Event) method public
  Reflection_Engine/Compute/RecordEvent.cs
  Reflection_Engine/Query/Events.cs
Labels: type:feature

#2325 Analytical_Engine: Add null checks to Geometry methods
  Analytical_Engine/Query/Geometry.cs
Labels: type:bug

#2327 Reflection_Engine: SortExtensionMethods improved to return the most relevant method
  Reflection_Engine/Modify/SortExtensionMethods.cs
Labels: type:feature

#2343 Geometry_Engine: IGeometry and IGeometry3D to check if ExtensionMethod is found before calling it to avoid exposing error when not relevant
  BHoM_Engine/Query/Geometry.cs
  BHoM_Engine/Query/Geometry3D.cs
Labels: type:bug

#2345 Reflection_Engine: SortExtensionMethods fixed to work on generics
  Reflection_Engine/Modify/SortExtensionMethods.cs
Labels: severity:critical, type:bug
