Repository BHoM/BHoM_Engine, pull requests merged in 2021-08, with the labels that each got.

#2586 Geometry_Engine: Added tolerance to Create PlanarSurface and methods it relies on
  Geometry_Engine/Compute/DistributeOutlines.cs
  Geometry_Engine/Create/PlanarSurface.cs
  Geometry_Engine/Query/Area.cs
Labels: type:feature

#2592 Geometry_Engine: DistributeOutlines fixed not to require the collection of openings not to be empty
  Geometry_Engine/Compute/DistributeOutlines.cs
Labels: type:bug

#2517 Structure_Engine: Fix Query.CoordinateSystem crashing on self-intersecting Panels
  Structure_Engine/Query/CoordinateSystem.cs
Labels: type:bug, type:compliance

#2602 Library_Engine: Add method for checking if Dataset is Prototype
  Library_Engine/Library_Engine.csproj
  Library_Engine/Query/IsPrototype.cs
Labels: type:feature
