Repository BHoM/BHoM_Engine, pull requests merged in 2021-07, with the labels that each got.

#2530 Verification: Make sure NullCheck method can call Generic methods
  .ci/code/Engine_Test/Verify/NullChecks.cs
Labels: type:bug

#2535 Reflection_Engine: Provide better support for setting a DateTime property with a string input
  Reflection_Engine/Modify/SetPropertyValue.cs
Labels: type:feature

#2536 MEP_Engine: Fix project reference to Matter Engine
  MEP_Engine/MEP_Engine.csproj
Labels: type:compliance

#2541 Environment_Engine: Bug fixes for various methods
  Environment_Engine/Compute/TidyPanels.cs
  Environment_Engine/Query/Bottom.cs
  Environment_Engine/Query/ExplodeToParts.cs
  Environment_Engine/Query/Sides.cs
  Environment_Engine/Query/Top.cs
Labels: type:bug

#2510 MEP_Engine: Add support for the new fitting object
  MEP_Engine/Modify/SetGeometry.cs
  MEP_Engine/Query/Geometry.cs
Labels: type:feature

#2542 Humans_Engine: Avalue analysis improvements
  Humans_Engine/Create/Spectator.cs
  Humans_Engine/Create/ViewCone.cs
  Humans_Engine/Create/ViewConeEnum/ViewConeType.cs
  Humans_Engine/Humans_Engine.csproj
  Humans_Engine/Modify/HeadOutline.cs
  Humans_Engine/Query/AvalueAnalysis.cs
  Humans_Engine/Query/Cartesian.cs
  Humans_Engine/Query/CvalueAnalysis.cs
  Humans_Engine/Query/EvalueAnalysis.cs
Labels: type:feature

#2562 Environment_Engine: Remove calls to GetShallowClone
  Environment_Engine/Modify/Transform.cs
Labels: type:compliance

#2566 Analytical_Engine: Replaced calls to IClone with calls to DeepClone
  Analytical_Engine/Modify/SetGeometry.cs
Labels: type:compliance

#2556 Physical_Engine: replace calls to GetShallowClone
  Physical_Engine/Modify/Transform.cs
Labels: type:compliance

#2567 Analytical_Engine: Add Region IsContaining method
  Analytical_Engine/Analytical_Engine.csproj
  Analytical_Engine/Query/IsContaining.cs
Labels: type:feature

#2563 Lighting_Engine: Remove calls to GetShallowClone
  Lighting_Engine/Modify/Transform.cs
Labels: type:compliance

#2564 Security_Engine: Remove calls to GetShallowClone
  Security_Engine/Modify/Transform.cs
Labels: type:compliance

#2558 MEP_Engine: replace calls to GetShallowClone
  MEP_Engine/Modify/Transform.cs
Labels: type:compliance

#2571 Diffing_Engine: DiffWithFragmentId to pass the DiffConfig correctly
  Diffing_Engine/Compute/DiffWithFragmentId.cs
Labels: type:bug

#2574 Structure_Engine: remove references to GetShallowClone
  Structure_Engine/Modify/Transform.cs
Labels: type:compliance
