Repository BHoM/BHoM_Engine, pull requests merged in 2021-11, with the labels that each got.

#2672 Environment_Engine Updated Method for isExternal.cs
  Environment_Engine/Query/IsExternal.cs
Labels: type:feature

#2693 Update TypesToFromJson.cs
  .ci/code/Serialiser_Test/Verify/TypesToFromJson.cs
Labels: type:compliance, priority:high

#2700 BHoM_Engine: Adding description to Create.Enumeration and Compute.ParseEnum
  BHoM_Engine/Create/Enumeration.cs
  Reflection_Engine/Compute/ParseEnum.cs
Labels: type:compliance

#2707 Structure_Engine: Add warping constants for tapered flange and angle sections
  Structure_Engine/Query/WarpingConstant.cs
Labels: type:feature

#2690 Reflection_Engine: LoadAllAssemblies refined to accept regular expression filters and allow parsing subfolders
  Reflection_Engine/Compute/LoadAllAssemblies.cs
Labels: type:feature

#2705 Architecture_Engine: Geometry() query for BuildersWork.Opening refactored to return Point
  Architecture_Engine/Query/Geometry.cs
Labels: type:bug
