Repository BHoM/BHoM_Engine, pull requests merged in 2022-06, with the labels that each got.

#2855 BHoM_Engine: fix Hash() method not working with CustomObjects
  BHoM_Engine/Query/Hash.cs
Labels: severity:critical, size:S, type:bug

#2857 Diffing_Engine: `IPropertyDifference.Description` to contain modified object Name by default when possible
  Diffing_Engine/Query/ObjectDifferences.cs
Labels: size:S, type:feature

#2865 Facade_Engine: MaterialComposition tweak to return valid empty value for valid empty frame edge
  Facade_Engine/Query/MaterialComposition.cs
Labels: type:bug
