Repository BHoM/BHoM_Engine, pull requests merged in 2022-07, with the labels that each got.

#2879 Humans_Engine: Fix CValue variable use
  Humans_Engine/Query/CvalueAnalysis.cs
Labels: severity:critical, type:bug

#2880 Architecture_Engine: Remove CleanRoom, version to use CleanRegion
  Analytical_Engine/Modify/CleanRegion.cs
  Architecture_Engine/Modify/CleanRoom.cs
Labels: type:compliance

#2877 Geometry_Engine: Added Query.FilterByNormal method
  Geometry_Engine/Query/FilterByNormal.cs
Labels: severity:low, size:S, type:feature

#2814 MEP_Engine: Update CircularEquivalentDiameter.cs
  MEP_Engine/Compute/CircularFlowAreaVelocity.cs
Labels: size:S, type:bug, priority:low
