Repository BHoM/BHoM_Engine, pull requests merged in 2022-01, with the labels that each got.

#2713 Reflection_Engine: LoadAllAssemblies fixed to load assemblies with dot in name
  Reflection_Engine/Compute/LoadAllAssemblies.cs
Labels: type:bug

#2733 Matter_Engine: Additional checks on Create for MaterialComposition
  Matter_Engine/Create/MaterialComposition.cs
Labels: type:compliance

#2635 Environment_Engine: Create openings from a panel
  Environment_Engine/Convert/OpeningFromPanel.cs
Labels: type:feature

#2538 Verification: Additional exceptions as errors for null checks
  .ci/code/Engine_Test/Verify/NullChecks.cs
Labels: type:compliance, type:feature
