Repository BHoM/BHoM_Engine, pull requests merged in 2022-05, with the labels that each got.

#2817 Environment_Engine: Add tolerance param to Opening
  Environment_Engine/Create/Opening.cs
  Environment_Engine/Query/IsContaining.cs
Labels: size:S, type:feature

#2821 Data_Engine: Set Name and Tag in AsCustomObject()
  Data_Engine/Query/ValuesAt.cs
Labels: type:bug

#2822 Structure_Engine: Add null check for reinforcement in material composition
  Structure_Engine/Query/MaterialComposition.cs
Labels: type:compliance

#2827 Data_Engine: handle empty tags
  Data_Engine/Query/ValuesAt.cs
Labels: type:bug

#2838 Results_Engine: Fix FilterBy not filtering by all properties.
  Results_Engine/Query/FilterResults.cs
Labels: type:bug

#2833 Data_Engine: Add Round method from TAS_Toolkit
  Data_Engine/Modify/Round.cs
Labels: type:compliance
