Repository BHoM/BHoM_Engine, pull requests merged in 2022-02, with the labels that each got.

#2746 Reflection_Engine: Include Replaced and ToBeRemoved back to the IsDeprecated check
  Reflection_Engine/Query/IsDeprecated.cs
Labels: type:compliance

#2741 Humans_Engine: Align with making ViewQualityResults immutable
  Humans_Engine/Query/AvalueAnalysis.cs
  Humans_Engine/Query/CvalueAnalysis.cs
  Humans_Engine/Query/EvalueAnalysis.cs
Labels: type:compliance

#2756 Geometry_Engine: Add empty bounds methods for Face, Basis and TransformMatrix
  Geometry_Engine/Query/Bounds.cs
Labels: type:compliance

#2752 Results_Engine: Simplifying Method Signature of DisplayMeshResults
  Results_Engine/Query/DisplayMeshResults.cs
Labels: type:feature

#2759 BHoM_Engine: Fix typos
  Physical_Engine/Create/Floor.cs
  Physical_Engine/Create/Roof.cs
  Physical_Engine/Create/Wall.cs
  Results_Engine/Query/MapResults.cs
  Structure_Engine/Query/Edges.cs
Labels: size:XS, type:compliance

#2760 CI: Exclusion added to the null checks
  .ci/code/Engine_Test/Verify/NullChecks.cs
Labels: type:compliance
