Repository BHoM/BHoM_Engine, pull requests merged in 2023-01, with the labels that each got.

#2978 .ci - Remove unit test that is poorly designed
  .ci/Datasets/Serialiser_Engine/Convert/ToJson.json
Labels: type:compliance

#2489 Spatial_Engine: Add FitPlane UnitTest for Spatial elements
  .ci/Datasets/Spatial_Engine/Compute/FitPlane.json
Labels: type:test-script

#2981 Environment_Engine: Adding null handling protection to IsShade method
  Environment_Engine/Query/IsShade.cs
Labels: type:compliance

#2982 Adding fallback method to IToSVGString(this IGeometry geometry)
  Graphics_Engine/Convert/ToSVGString.cs
Labels: type:compliance

#2985 Speech_Engine: Remove legacy prototype code
  Speech_Engine/CommandProcessor.cs
  Speech_Engine/SpeakText.cs
  Speech_Engine/Speech_Engine.csproj
Labels: type:compliance

#2984 Base_Engine: Fix issues initialising some Random objects
  .ci/Datasets/BHoM_Engine/Create/RandomObject.json
  BHoM_Engine/Create/IObject/RandomObject.cs
Labels: type:bug

#2991 Geometry_Engine: project along lowercase character compliance
  Geometry_Engine/Modify/ProjectAlong.cs
Labels: type:compliance

#2993 BHoM_Engine: Remove failing unit test on random object generation
  .ci/Datasets/BHoM_Engine/Create/RandomObject.json
Labels: type:compliance

#2996 Serialiser_Engine: Prevent duplicated types being registered
  Serialiser_Engine/Compute/RegisterClassMap.cs
Labels: type:bug
