Repository BHoM/BHoM_Engine, pull requests merged in 2023-11, with the labels that each got.

#3205 Serialiser_Engine: Fix stack overflow when deserialising nullable items
  Serialiser_Engine/Compute/Deserialise/Nullable.cs
Labels: type:bug

#3203 Environment_Engine: Refactor of IsContaining and ElementsInSpace methods to Geometry and Analytical namespaces as appropriate
  Analytical_Engine/Compute/ElementsInRegion.cs
  Analytical_Engine/Compute/ExtrudeToVolume.cs
  Analytical_Engine/Query/IsContaining.cs
  Environment_Engine/Environment_Engine.csproj
  Environment_Engine/Query/IsContaining.cs
  Geometry_Engine/Query/IsContaining.cs
Labels: type:feature

#3215 Environment_Engine: adding replace space name method
  Environment_Engine/Modify/ReplaceSpaceName.cs
Labels: type:feature

#3217 Security_Engine: Fixed documentation compliance
  Security_Engine/Compute/CameraFieldOfView.cs
Labels: type:documentation

#3220 BHoM_Engine: replaced C:/ProgramData with SpecialFolder construct
  BHoM_Engine/Query/BHoMFolder.cs
Labels: type:compliance

#3221 BHoM_Engine: Replaced C:\ProgramData with SpecialFolder construct
  BHoM_Engine/Query/BHoMFolder.cs
  Library_Engine/Query/IsPrototype.cs
  Library_Engine/Query/Library.cs
  Library_Engine/Query/LibrarySettings.cs
  Reflection_Engine/Query/IsPrototype.cs
  Versioning_Engine/Convert/ToNewVersion.cs
Labels: type:feature

#3213 Structure_Engine: Added an additional Create Method for GeometricalLineLoad
  Structure_Engine/Create/Loads/GeometricalLineLoad.cs
Labels: type:feature

#3222 Update README.md
  README.md
Labels: type:documentation
