Repository BHoM/BHoM_Engine, pull requests merged in 2023-08, with the labels that each got.

#3120 Geometry_Engine: Fix spelling in input attribute of RowEchelonForm
  Geometry_Engine/Compute/RowEchelonForm.cs
Labels: type:documentation

#3122 Geometry_Engine: Fix spelling of description in CountNonZeroRows
  Geometry_Engine/Compute/CountNonZeroRows.cs
Labels: type:documentation

#3124 Environment_Engine: Renaming input in the Transform.cs
  Environment_Engine/Modify/Transform.cs
Labels: type:documentation

#3127 Geometry_Engine: Fix code comment spelling
  Geometry_Engine/Query/Normal.cs
Labels: type:documentation

#3134 Serialiser_Engine: Force invariant representation of number in serialisation
  Serialiser_Engine/Compute/Deserialise/Decimal.cs
  Serialiser_Engine/Compute/Deserialise/Double.cs
  Serialiser_Engine/Compute/Deserialise/String.cs
Labels: type:bug

#3143 Environment_Engine: UX improvement on panel creation
  Environment_Engine/Create/Panel.cs
  Geometry_Engine/Query/InternalEdges.cs
Labels: type:compliance

#3144 Serialiser_Engine: Improve size of JSON by excluding empty IBHoMObject properties
  Serialiser_Engine/Compute/Serialise/IBHoMObject.cs
Labels: type:feature

#3149 BHoM_Engine: Add ParseEnum method for int value and add ignoreCase option for string conversion
  BHoM_Engine/Compute/ParseEnum.cs
Labels: type:feature

#3147 Diffing_Engine: InputObjectsNullOrEmpty method bugfixed
  Diffing_Engine/Compute/IDiffing.cs
Labels: type:bug

#3148 Base_Engine: Remove Base Engine Set Geometry method
  BHoM_Engine/Modify/SetGeometry.cs
  BHoM_Engine/Versioning_63.json
Labels: type:compliance

#3159 .ci Unit Tests - fix compilation
  .ci/unit-tests/Base_Engine_Tests/Base_Engine_Tests.csproj
  .ci/unit-tests/Serialiser_Engine_Tests/CompareNewAndOldToJson.cs
  .ci/unit-tests/Serialiser_Engine_Tests/Serialiser_Engine_Tests.csproj
  .ci/unit-tests/Serialiser_Engine_Tests/ToFromJson.cs
  .ci/unit-tests/Serialiser_Engine_Tests/Versioning.cs
  .ci/unit-tests/Structure_Engine_Tests/Structure_Engine_Tests.csproj
Labels: type:compliance

#3163 Settings_Engine: Fix output path
  Settings_Engine/Settings_Engine.csproj
Labels: type:bug

#3157 Environment_Engine: Update PanelsContainingPoint to also return the panels not containing the point
  Environment_Engine/Modify/AddOpening.cs
  Environment_Engine/Query/PanelsContainingPoint.cs
Labels: type:feature
