Repository BHoM/BHoM_Engine, pull requests merged in 2023-09, with the labels that each got.

#3165 Geometry_Engine: Add shortest path algorithm
  Geometry_Engine/Compute/ShortestPath.cs
Labels: type:feature

#3169 Serialiser_Engine: Protect against BSON having no values in list deserialisation
  Serialiser_Engine/Compute/Deserialise/List.cs
Labels: type:bug

#3170 Environment_Engine: Intuitive default environmental panel types
  Environment_Engine/Create/Panel.cs
  Environment_Engine/Modify/SetFloorPanels.cs
  Environment_Engine/Modify/SetRoofPanels.cs
  Environment_Engine/Modify/SetWallPanels.cs
Labels: type:feature

#3180 Environment_Engine: Update AssignSpaceTypeByPoint to provide output of spaces not assigned
  Environment_Engine/Compute/AssignSpaceTypeByPoint.cs
Labels: type:user-experience

#3182 Geometry_Engine: Changing from colleciton to collection in IsContaining.
  Geometry_Engine/Query/IsContaining.cs
Labels: type:documentation

#3184 Settings_Engine: Default to not loading all directories when loading settings
  Settings_Engine/Compute/LoadSettings.cs
Labels: type:bug

#3186 Environment_Engine: Control of duplicate control points before extruding to volume
  Environment_Engine/Compute/ExtrudeToVolume.cs
Labels: type:user-experience
