Repository BHoM/BHoM_Engine, pull requests merged in 2023-10, with the labels that each got.

#3190 Environment_Engine: Changing note wording
  Environment_Engine/Modify/AssignGenericConstructions.cs
Labels: type:compliance

#3191 BHoM_Engine: RunExtensionMethodAsync and TryRunExtensionMethodAsync added
  BHoM_Engine/Compute/RunExtensionMethod.cs
  BHoM_Engine/Compute/TryRunExtensionMethod.cs
Labels: type:feature

#3193 Analytical_Engine: Resolve Dictionary Key Duplication Error
  Analytical_Engine/Create/Graph/Graph.cs
Labels: type:bug

#3197 .ci: removed duplicate reference
  .ci/BHoMBot/Nuget/BHoM.Engine.nuspec
Labels: type:compliance

#3195 Environment_Engine: Added ElementsInSpace and dependant IsContaining methods / optimisations
  Environment_Engine/Compute/ElementsInSpace.cs
  Environment_Engine/Query/IsContaining.cs
  Lighting_Engine/Query/Geometry.cs
Labels: type:feature
