Repository BHoM/BHoM_Engine, pull requests merged in 2024-09, with the labels that each got.

#3414 Verifiaction: Add reference to Diffing_Engine to properly access the IsEqual method
  .ci/code/Engine_Test/Verify/NullChecks.cs
  .ci/code/Serialiser_Test/Serialiser_Test.csproj
  .ci/code/Serialiser_Test/Verify/MethodsToFromJson.cs
  .ci/code/Serialiser_Test/Verify/ObjectsToFromJson.cs
  .ci/code/Serialiser_Test/Verify/TypesToFromJson.cs
Labels: severity:critical, type:bug

#3412 Structure_Engine: Update `PileFoundation` Geometry method
  Structure_Engine/Query/Geometry.cs
Labels: type:bug

#3410 Diffing_Engine: Do not include static properties and fields in differences
  Diffing_Engine/Query/DifferentProperties.cs
  Diffing_Engine/Query/NumericalDifferenceInclusion.cs
  Diffing_Engine/Query/ObjectDifferences.cs
Labels: type:bug, type:feature
