Repository BHoM/BHoM_Engine, pull requests merged in 2024-07, with the labels that each got.

#3364 Serialiser_Engine: Update NullOrEmptyCheck to just check for Null
  .ci/Datasets/Structure_Engine/Create/CellularSectionFromBaseSection.json
  Serialiser_Engine/Compute/Serialise/IBHoMObject.cs
Labels: type:compliance

#3369 Geometry_Engine: BooleanDifference secured against single-dimensional regions
  Geometry_Engine/Compute/BooleanDifference.cs
Labels: type:bug

#3371 Serialiser_Engine: fix for MessageForDeleted to be picked up for properties of types that have multiple matching types
  BHoM_Engine/Create/Type/Type.cs
  Serialiser_Engine/Compute/Deserialise/Type.cs
Labels: type:bug

#3375 Ground_Engine: Remove blankGeology from Stratum Create method
  Ground_Engine/Create/Stratum.cs
Labels: type:feature

#3377 Search_Engine: Update unit tests for ExtractAll, ExtractTop, ExtractSorted and MatchScore
  .ci/Datasets/Search_Engine/Compute/ExtractAll.json
  .ci/Datasets/Search_Engine/Compute/ExtractSorted.json
  .ci/Datasets/Search_Engine/Compute/ExtractTop.json
  .ci/Datasets/Search_Engine/Compute/MatchScore.json
Labels: type:bug

#3363 Structure_Engine: Fixed bug where PanelToFEMesh returned an error
  .ci/Datasets/Geometry_Engine/Query/DiscontinuityPoints.json
  .ci/Datasets/Structure_Engine/Convert/FEMeshToPanel.json
  .ci/Datasets/Structure_Engine/Convert/PanelToFEMesh.json
  .ci/Datasets/Structure_Engine/Create/CellularSectionFromBaseSection.json
  Analytical_Engine/Query/IsOutlineTrianglular.cs
  Geometry_Engine/Query/DiscontinuityPoints.cs
  Structure_Engine/Convert/PanelToFEMesh.cs
Labels: type:bug

#3372 Ground_Engine: Consolidate method for a Borehole
  Ground_Engine/Compute/ConsolidateStrata.cs
  Ground_Engine/Create/Borehole.cs
  Ground_Engine/Create/ContaminantSample.cs
Labels: type:feature

#3379 Ground_Engine, BHoM_Engine: Add UnitTests for ConsolidateStrata, remove UTs for GeometryHash
  .ci/Datasets/BHoM_Engine/Query/GeometryHash.json
  .ci/Datasets/Ground_Engine/Compute/ConsolidateStrata.json
Labels: type:compliance

#3381 Structure_Engine: Update UT for CellularSection
  .ci/Datasets/Structure_Engine/Create/CellularSectionFromBaseSection.json
Labels: type:compliance
