Repository BHoM/BHoM_Engine, pull requests merged in 2024-02, with the labels that each got.

#3268 Diffing_Engine: Hash and Diff to leverage new GeometryHash
  BHoM_Engine/Query/Hash.cs
  Geometry_Engine/Query/GeometryHash.cs
  Geometry_Engine/Query/HashArray.cs
Labels: type:feature

#3274 BHoM_Engine: wrapping fixed in ShiftList method
  BHoM_Engine/Modify/ShiftList.cs
Labels: type:bug

#3266 Security_Engine: Camera Field of View bug fix
  Security_Engine/Compute/CameraFieldOfView.cs
  Security_Engine/Modify/SimplifyCameraFieldOfView.cs
  Security_Engine/Query/ViewCone.cs
Labels: type:bug

#3276 Serialiser_Engine: Stop throwing error on System.DBNull
  Serialiser_Engine/Compute/Serialise.cs
Labels: type:bug

#3275 Geometry_Engine: Optimisation and OutlinesFromLines
  Geometry_Engine/Compute/BooleanDifference.cs
  Geometry_Engine/Compute/BooleanIntersection.cs
  Geometry_Engine/Compute/BooleanUnion.cs
  Geometry_Engine/Compute/FitLine.cs
  Geometry_Engine/Compute/Split.cs
  Geometry_Engine/Modify/RoundCoordinates.cs
  Geometry_Engine/Query/IsCollinear.cs
  Geometry_Engine/Query/IsCoplanar.cs
Labels: type:feature

#3258 Environment_Engine: Compute Openings from a list of panels and a glazing ratio
  Environment_Engine/Compute/OpeningsFromGlazingRatio.cs
Labels: type:feature

#3281 BHoM_Engine: Use NetStandard version of DeepCloner in Nugets rather than NetFramework
  .ci/BHoMBot/Nuget/BHoM.Engine.nuspec
Labels: type:compliance

#3280 Geometry_Engine: Singular Value Decomposition implemented and applied to FitLine
  Geometry_Engine/Compute/FitLine.cs
  Geometry_Engine/Compute/SingularValueDecomposition.cs
Labels: type:bug

#3283 Geometry_Engine: Split bugs fixed and OutlinesFromLines method added
  Architecture_Engine/Compute/CeilingTiles.cs
  BHoM_Engine/Query/IsNull.cs
  Geometry_Engine/Compute/BooleanUnion.cs
  Geometry_Engine/Compute/OutlinesFromLines.cs
  Geometry_Engine/Compute/Split.cs
  Geometry_Engine/Query/IsCollinear.cs
Labels: type:feature

#3296 Settings_Engine: Ensure SaveSettings also updates settings in memory
  Settings_Engine/Compute/SaveSettings.cs
Labels: type:feature

#3292 Geometry_Engine: split at self intersections method added
  Geometry_Engine/Compute/SplitAtSelfIntersections.cs
Labels: type:feature

#3290 Geometry_Engine: Singular Value Decomposition algorithm applied to FitPlane method
  Geometry_Engine/Compute/FitPlane.cs
Labels: type:feature

#3293 Geometry_Engine: Tolerance introduced to the check of 2-dimensionality of the input point set
  Geometry_Engine/Compute/FitLine.cs
Labels: type:feature

#3300 Settings_Engine: Add LoadSettings method for loading a single settings file
  Settings_Engine/Compute/LoadSettings.cs
  Settings_Engine/Compute/SaveSettings.cs
Labels: type:feature

#3302 BHoM_Engine: Fix ThrowError confusion for developers
  BHoM_Engine/Compute/RecordEvent.cs
  BHoM_Engine/Compute/ThrowErrorsAsExceptions.cs
Labels: type:user-experience

#3304 Settings_Engine: Change LoadSettings method name to avoid conflicts
  Settings_Engine/Compute/LoadSettings.cs
Labels: type:bug
