Repository BHoM/BHoM_Engine, pull requests merged in 2024-12, with the labels that each got.

#3433 Verification_Engine - Report Message null checks added
  Verification_Engine/Query/ReportMessage.cs
Labels: type:bug

#3440 BHoM_Engine: documentation compliance fixed
  .ci/unit-tests/Base_Engine_Tests/Compute/TryRunExtensionMethod.cs
  BHoM_Engine/Query/NumericalApproximation.cs
Labels: type:compliance

#3443 Add proper protection for IsEquals check for Serialisation
  .ci/code/Serialiser_Test/Verify/ObjectsToFromJson.cs
  Diffing_Engine/Diffing_Engine.csproj
Labels: type:bug

#3449 Structure_Engine: Unitise normal vector and add quantities to descriptions
  Structure_Engine/Create/Elements/RetainingWall.cs
Labels: type:feature
