Repository BHoM/BHoM_Engine, pull requests merged in 2024-06, with the labels that each got.

#3350 BHoM_Engine: Modify.SortExtensionMethods fixed not to exclude methods targeting object
  BHoM_Engine/Modify/SortExtensionMethods.cs
Labels: type:bug

#3348 Structure_Engine: Add Geometry3D method for Pile, PileCap and PileFoundation
  Structure_Engine/Query/Geometry3D.cs
Labels: type:feature

#3362 Update AssemblyFileVersion to 7.3
  .ci/code/Engine_Test/Engine_Test.csproj
  .ci/code/Serialiser_Test/Serialiser_Test.csproj
  .ci/unit-tests/Base_Engine_Tests/Base_Engine_Tests.csproj
  .ci/unit-tests/Serialiser_Engine_Tests/Serialiser_Engine_Tests.csproj
  .ci/unit-tests/Structure_Engine_Tests/Structure_Engine_Tests.csproj
  Acoustic_Engine/Acoustic_Engine.csproj
  Analytical_Engine/Analytical_Engine.csproj
  Architecture_Engine/Architecture_Engine.csproj
  BHoM_Engine/BHoM_Engine.csproj
  BHoM_Engine/Create/Type/GenericType.cs
  BHoM_Engine/Create/Type/Type.cs
  Data_Engine/Data_Engine.csproj
  Diffing_Engine/Diffing_Engine.csproj
  Environment_Engine/Environment_Engine.csproj
  Facade_Engine/Facade_Engine.csproj
  Geometry_Engine/Geometry_Engine.csproj
  Graphics_Engine/Graphics_Engine.csproj
  Ground_Engine/Ground_Engine.csproj
  Humans_Engine/Humans_Engine.csproj
  Library_Engine/Library_Engine.csproj
  Lighting_Engine/Lighting_Engine.csproj
  MEP_Engine/MEP_Engine.csproj
  Matter_Engine/Compute/AggregateMaterialComposition.cs
  Matter_Engine/Matter_Engine.csproj
  Physical_Engine/Physical_Engine.csproj
  Planning_Engine/Planning_Engine.csproj
  Programming_Engine/Programming_Engine.csproj
  Reflection_Engine/Reflection_Engine.csproj
  Results_Engine/Results_Engine.csproj
  Search_Engine/Search_Engine.csproj
  Security_Engine/Security_Engine.csproj
  Serialiser_Engine/Serialiser_Engine.csproj
  Settings_Engine/Settings_Engine.csproj
  Spatial_Engine/Spatial_Engine.csproj
  Structure_Engine/Query/Elements0D.cs
  Structure_Engine/Structure_Engine.csproj
  Versioning_Engine/Versioning_Engine.csproj
Labels: type:compliance
