Repository BHoM/BHoM_Engine, pull requests merged in 2024-08, with the labels that each got.

#3391 Serialiser_Engine: Various changes to get unit-tests functional
  .ci/Datasets/Reflection_Engine/Query/DocumentationURL.json
  .ci/Datasets/Reflection_Engine/Query/IsPrototype.json
  .ci/Datasets/Reflection_Engine/Query/Url.json
  .ci/unit-tests/Serialiser_Engine_Tests/AllTypesIObject.cs
  .ci/unit-tests/Serialiser_Engine_Tests/SystemTypesToFromJson.cs
  .ci/unit-tests/Serialiser_Engine_Tests/Versioning.cs
  .ci/unit-tests/Structure_Engine_Tests/Query/IGeometry.cs
  BHoM_Engine/Create/Type/Type.cs
  Structure_Engine/Query/Geometry.cs
Labels: type:compliance, type:test-script

#3397 BHoM_Engine: null inputs enabled in TryRunExtensionMethod
  BHoM_Engine/Compute/MakeGenericFromInputs.cs
  BHoM_Engine/Compute/TryRunExtensionMethod.cs
  BHoM_Engine/Query/ExtensionMethodHierarchy.cs
  BHoM_Engine/Query/ExtensionMethodToCall.cs
  BHoM_Engine/Query/IsNullable.cs
  BHoM_Engine/Versioning_73.json
Labels: type:feature

#3399 BHoM_Engine: Additional check for assembly qualified type without version for Create EngineType
  BHoM_Engine/Create/Type/EngineType.cs
Labels: type:bug
