Repository BHoM/BHoM_Engine, pull requests merged in 2024-05, with the labels that each got.

#3344 BHoM_Engine: creation of type in case of multiple matching types fixed
  BHoM_Engine/Create/Type/AllTypes.cs
  BHoM_Engine/Create/Type/GenericType.cs
  BHoM_Engine/Create/Type/Type.cs
  Serialiser_Engine/Compute/Deserialise/Type.cs
Labels: type:bug

#3338 Diffing_Engine: IsEqual method added
  Diffing_Engine/Compute/DiffOneByOne.cs
  Diffing_Engine/Compute/DiffRevisions.cs
  Diffing_Engine/Compute/DiffWithCustomIds.cs
  Diffing_Engine/Query/DifferentProperties.cs
  Diffing_Engine/Query/IsEqual.cs
  Diffing_Engine/Query/ObjectDifferences.cs
Labels: type:feature

#3346 Spatial_Engine: Update failing UTs in Spatial engine
  .ci/Datasets/Spatial_Engine/Compute/FitPlane.json
  .ci/Datasets/Spatial_Engine/Modify/RoundCoordinates.json
Labels: type:test-script

#3351 Structure_Engine: Add method required for new BuiltUpDoubleRibbed surface property
  Structure_Engine/Query/Description.cs
  Structure_Engine/Query/MassPerArea.cs
  Structure_Engine/Query/MaterialComposition.cs
  Structure_Engine/Query/TotalThickness.cs
  Structure_Engine/Query/VolumePerArea.cs
Labels: type:feature
