Repository BHoM/BHoM_Engine, pull requests merged in 2024-01, with the labels that each got.

#3230 Geometry_Engine & Structure_Engine: Update documentation links
  Geometry_Engine/Query/IsVertical.cs
  Structure_Engine/Compute/ShearAreaPolyline.cs
  Structure_Engine/Query/IsVertical.cs
  Structure_Engine/Query/ShearArea.cs
Labels: type:documentation

#3231 Structure_Engine: Checking if property is null in AnalyticalBars
  Structure_Engine/Query/AnalyticalBars.cs
Labels: type:user-experience

#3233 Reflection_Engine: support methods for legacy attributes removed
  Reflection_Engine/Query/IsReleased.cs
  Reflection_Engine/Versioning_71.json
Labels: type:compliance

#3232 Geometry_Engine: redundant calls to clone removed
  Geometry_Engine/Compute/BooleanDifference.cs
  Geometry_Engine/Compute/BooleanIntersection.cs
  Geometry_Engine/Compute/BooleanUnion.cs
  Geometry_Engine/Compute/ClusterCollinear.cs
  Geometry_Engine/Compute/DistributeOutlines.cs
  Geometry_Engine/Compute/SortAlongCurve.cs
  Geometry_Engine/Compute/SortCollinear.cs
  Geometry_Engine/Compute/WetBlanketInterpretation.cs
  Geometry_Engine/Convert/NurbsForm.cs
  Geometry_Engine/Create/Plane.cs
  Geometry_Engine/Modify/CollapseToPolyline.cs
  Geometry_Engine/Modify/Mirror.cs
  Geometry_Engine/Modify/Normalise.cs
  Geometry_Engine/Modify/Project.cs
  Geometry_Engine/Modify/ProjectAlong.cs
  Geometry_Engine/Modify/SetGeometry.cs
  Geometry_Engine/Modify/SortCurves.cs
  Geometry_Engine/Modify/SplitAtPoints.cs
  Geometry_Engine/Modify/Transform.cs
  Geometry_Engine/Modify/Translate.cs
  Geometry_Engine/Query/Area.cs
  Geometry_Engine/Query/Bounds.cs
  Geometry_Engine/Query/ExternalEdges.cs
  Geometry_Engine/Query/InternalEdges.cs
  Geometry_Engine/Query/IsClockwise.cs
  Geometry_Engine/Query/IsCoplanar.cs
Labels: type:compliance

#3234 Geometry_Engine: make all methods extension methods.
  Geometry_Engine/Convert/Polyline.cs
  Geometry_Engine/Query/Integration.cs
  Geometry_Engine/Query/SliceAt.cs
Labels: type:compliance

#3236 Structure_Engine: Rename StartNode/EndNode to Start/End
  Analytical_Engine/Convert/Graph/ToRelation.cs
  Analytical_Engine/Modify/SetElements0D.cs
  Analytical_Engine/Modify/SetGeometry.cs
  Analytical_Engine/Query/Elements0D.cs
  Analytical_Engine/Query/Geometry.cs
  Structure_Engine/Compute/MapTaperedProfile.cs
  Structure_Engine/Create/Elements/Bar.cs
  Structure_Engine/Create/Loads/BarVaryingDistributedLoad/BarVaryingDistributedLoadDistanceBothEnds.cs
  Structure_Engine/Modify/Flip.cs
  Structure_Engine/Modify/SetElements0D.cs
  Structure_Engine/Modify/Transform.cs
  Structure_Engine/Objects/EqualityComparers/BarEndNodesDistanceComparer.cs
  Structure_Engine/Query/BarSectionTranformation.cs
  Structure_Engine/Query/Centreline.cs
  Structure_Engine/Query/CoordinateSystem.cs
  Structure_Engine/Query/DeformedShape.cs
  Structure_Engine/Query/DistributedPoints.cs
  Structure_Engine/Query/IsNull.cs
  Structure_Engine/Query/OppositeNode.cs
  Structure_Engine/Query/PlotBarForce.cs
  Structure_Engine/Query/Tangent.cs
  Structure_Engine/Query/Visualize.cs
Labels: type:compliance

#3238 Analytical_Engine: Align with Graph namespace elevation
  Analytical_Engine/Convert/Graph/ToDataVizObjects.cs
  Analytical_Engine/Convert/Graph/ToDotFormat.cs
  Analytical_Engine/Convert/Graph/ToRelation.cs
  Analytical_Engine/Create/Graph/Graph.cs
  Analytical_Engine/Create/Graph/Relation.cs
  Analytical_Engine/Modify/Graph/ProjectGraph.cs
  Analytical_Engine/Modify/Graph/RelationCurves.cs
  Analytical_Engine/Modify/Graph/RemoveEntity.cs
  Analytical_Engine/Modify/Graph/RemoveIsolatedEntities.cs
  Analytical_Engine/Modify/Graph/Reverse.cs
  Analytical_Engine/Modify/Graph/UniqueEntities.cs
  Analytical_Engine/Modify/Graph/UniqueEntityNames.cs
  Analytical_Engine/Query/Geometry.cs
  Analytical_Engine/Query/Graph/AStarShortestPath.cs
  Analytical_Engine/Query/Graph/Adjacency.cs
  Analytical_Engine/Query/Graph/Depth.cs
  Analytical_Engine/Query/Graph/Destinations.cs
  Analytical_Engine/Query/Graph/DijkstraShortestPath.cs
  Analytical_Engine/Query/Graph/Entities.cs
  Analytical_Engine/Query/Graph/Entity.cs
  Analytical_Engine/Query/Graph/EntityNeighbourhood.cs
  Analytical_Engine/Query/Graph/FilterEntities.cs
  Analytical_Engine/Query/Graph/FilterRelations.cs
  Analytical_Engine/Query/Graph/Incoming.cs
  Analytical_Engine/Query/Graph/IsolatedEntities.cs
  Analytical_Engine/Query/Graph/NotSinks.cs
  Analytical_Engine/Query/Graph/Relation.cs
  Analytical_Engine/Query/Graph/RelationArrow.cs
  Analytical_Engine/Query/Graph/RelationLength.cs
  Analytical_Engine/Query/Graph/Sinks.cs
  Analytical_Engine/Query/Graph/Sources.cs
  Analytical_Engine/Query/Graph/SubGraphs.cs
Labels: type:compliance

#3239 Data_Engine: Remove redundant filter query
  Data_Engine/Compute/FilterData.cs
  Data_Engine/Query/Filter.cs
Labels: type:compliance

#3242 Diffing_Engine: Align to changes from Id to ID
  Diffing_Engine/Compute/DiffWithCustomIds.cs
  Diffing_Engine/Convert/TryParseObjectToGuid.cs
  Diffing_Engine/Create/Delta.cs
Labels: type:compliance

#3244 Spatial_Engine: Remove unnecessary area methods
  Spatial_Engine/Query/Area.cs
  Spatial_Engine/Versioning_71.json
Labels: type:compliance

#3240 Structure_Engine: Align with removal of deprecated reinforcement objects
  Structure_Engine/Create/Reinforcement/Reinforcement.cs
  Structure_Engine/Query/IsLongitudinal.cs
  Structure_Engine/Query/IsNull.cs
  Structure_Engine/Query/TieDiameter.cs
  Structure_Engine/Versioning_71.json
Labels: type:compliance

#3245 NewInternalElementXD moved to Query class
  Analytical_Engine/Query/IElement2D/NewInternalElement2D.cs
  Environment_Engine/Versioning_71.json
  Geometry_Engine/Create/IElement2D/NewInternalElement2D.cs
  Geometry_Engine/Query/IElement2D/NewInternalElement2D.cs
  Physical_Engine/Create/IElement/IElement1D/NewElement1D.cs
  Physical_Engine/Create/IElement/IElement2D/NewInternalElement2D.cs
  Physical_Engine/Query/IElement/IElement2D/NewInternalElement2D.cs
  Physical_Engine/Versioning_71.json
  Spatial_Engine/Create/NewElement0D.cs
  Spatial_Engine/Create/NewElement1D.cs
  Spatial_Engine/Create/NewInternalElement2D.cs
  Spatial_Engine/Query/NewInternalElement2D.cs
  Spatial_Engine/Versioning_71.json
Labels: type:compliance

#3246 BHoM_Engine: Remove deprecated methods
  Architecture_Engine/Query/NewElement1D.cs
  Architecture_Engine/Versioning_71.json
  Diffing_Engine/Query/ListModifiedProperties.cs
  Diffing_Engine/Versioning_71.json
  Environment_Engine/Query/CleanSpace.cs
  Environment_Engine/Query/FilterPanels.cs
  Environment_Engine/Versioning_71.json
  Geometry_Engine/Query/Centre.cs
  Geometry_Engine/Query/Radius.cs
  Geometry_Engine/Versioning_71.json
  Structure_Engine/Convert/FEMeshToPanel.cs
  Structure_Engine/Create/Elements/Panel.cs
  Structure_Engine/Create/Loads/AreaUniformlyDistributedLoad.cs
  Structure_Engine/Create/Loads/BarUniformTemperatureLoad.cs
  Structure_Engine/Create/Loads/ContourLoad.cs
  Structure_Engine/Create/Loads/GeometricalLineLoad.cs
  Structure_Engine/Create/Loads/Load.cs
  Structure_Engine/Create/Requests/FilterRequest.cs
  Structure_Engine/Versioning_71.json
Labels: type:compliance

#3248 BHoM_Engine: Replace \\ in description attributes with /
  BHoM_Engine/Query/BHoMFolder.cs
Labels: type:compliance

#3250 Spatial_Engine: Update description for create CircleProfile
  Spatial_Engine/Create/ShapeProfiles/CircleProfile.cs
Labels: type:bug

#3256 Structure_Engine: Fix bug for the Mass method (for Panels)
  .ci/Datasets/Structure_Engine/Query/Mass.json
  Structure_Engine/Query/Mass.cs
Labels: type:bug

#3257 Geometry_Engine: implement GeometryHash as a single value
  BHoM_Engine/Modify/PropertyNamesToFullNames.cs
  BHoM_Engine/Query/GeometryHash.cs
  BHoM_Engine/Query/Hash.cs
  Geometry_Engine/Query/GeometryHash.cs
  Geometry_Engine/Query/HashArray.cs
  Geometry_Engine/Versioning_71.json
Labels: type:feature

#3247 Search_Engine: Migrate Search_Engine to BHoM_Engine
  .ci/Datasets/Search_Engine/Compute/ExtractAll.json
  .ci/Datasets/Search_Engine/Compute/ExtractSorted.json
  .ci/Datasets/Search_Engine/Compute/ExtractTop.json
  .ci/Datasets/Search_Engine/Compute/MatchScore.json
  .github/CODEOWNERS
  BHoM_Engine.sln
  Search_Engine/Compute/Extract/ExtractAll.cs
  Search_Engine/Compute/Extract/ExtractSorted.cs
  Search_Engine/Compute/Extract/ExtractTop.cs
  Search_Engine/Compute/Ratios/FuzzyMatch.cs
  Search_Engine/Search_Engine.csproj
Labels: type:feature
