Repository BHoM/BHoM_Engine, pull requests merged in 2025-06, with the labels that each got.

#3509 Verification_Engine: references fixed
  Verification_Engine/Verification_Engine.csproj
Labels: type:compliance

#3516 Verification_Engine: capturing events enabled in Requirement verification
  Verification_Engine/Compute/VerifyCondition.cs
  Verification_Engine/Compute/VerifyRequirement.cs
  Verification_Engine/Compute/VerifySpecification.cs
Labels: type:feature

#3520 Verification_Engine: UTs added
  .ci/Datasets/Verification_Engine/Compute/VerifyCondition.json
  .ci/Datasets/Verification_Engine/Compute/VerifySpecification.json
  .ci/Datasets/Verification_Engine/Query/Passes.json
  .ci/Datasets/Verification_Engine/Query/ReportMessage.json
Labels: type:test-script

#3522 Default message for stack trace for verisoning
  Versioning_Engine/Convert/ToNewVersion.cs
Labels: type:bug
