Repository BHoM/BHoM_Engine, pull requests merged in 2025-03, with the labels that each got.

#3467 Verification_Engine: extraction of nested properties via TryGetValueFromSource fixed
  Verification_Engine/Compute/TryGetValueFromSource.cs
  Verification_Engine/Compute/VerifyCondition.cs
Labels: type:bug

#3468 Structure_Engine: Geometry3D Panel Extrusion method using wrong thickness and normal vector
  Structure_Engine/Query/Geometry3D.cs
Labels: type:bug

#3471 Fallback on versioning to upgrade via pipes if direct calling crashes
  Versioning_Engine/Convert/ToNewVersion.cs
Labels: severity:critical, type:bug

#3475 Verification_Engine: code tweaked to enable special treatment of Revit parameters
  Verification_Engine/Compute/CompareValues.cs
  Verification_Engine/Compute/VerifyCondition.cs
  Verification_Engine/Query/FormulaComponent.cs
  Verification_Engine/Query/HasValue.cs
Labels: type:bug

#3474 Add missing descriptions for Tests
  .ci/unit-tests/Base_Engine_Tests/Query/IsNumeric.cs
  .ci/unit-tests/Base_Engine_Tests/Query/IsNumericIntegralType.cs
  .ci/unit-tests/Base_Engine_Tests/Query/Unpack.cs
  .ci/unit-tests/Serialiser_Engine_Tests/BaseLoader.cs
  .ci/unit-tests/Serialiser_Engine_Tests/Helpers/CanReplaceMethodWithType.cs
  .ci/unit-tests/Serialiser_Engine_Tests/Helpers/TemporaryLogFolder.cs
  .ci/unit-tests/Serialiser_Engine_Tests/Helpers/TemporaryLogPath.cs
  .ci/unit-tests/Structure_Engine_Tests/Query/Geometry.cs
  .ci/unit-tests/Structure_Engine_Tests/Query/Geometry3D.cs
Labels: type:compliance

#3464 BHoM_Engine: Exclude SpecialName methods from BhoMMethodList
  BHoM_Engine/Compute/ExtractAssembly.cs
Labels: type:bug

#3485 release build fixed for Verification_Engine
  Verification_Engine/Verification_Engine.csproj
Labels: type:bug
